#include "irred/thermal_neutrino.hpp"
#include <array>
#include <cfenv>
#include <cmath>
#include <iostream>
#include <limits>
#include <numbers>
#include <stdexcept>
#include <type_traits>
#include <utility>
using namespace irred::cosmology;
using S = irred::numerics::Status;
int main() {
  unsigned checks=0;
  auto require=[&](bool b,const char *message) {
    ++checks; if (!b) throw std::runtime_error(message);
  };
  auto close=[&](long double actual,long double expected,long double rel=2e-10L) {
    require(std::abs(actual-expected)<=1e-10L+rel*std::abs(expected),"analytic comparison allocation");
  };
  ThermalPolicy p;
  const long double pi=std::numbers::pi_v<long double>;
  const long double exact=7*pi*pi*pi*pi/120;
  auto m=evaluate_thermal_moments(0,p);
  require(m.status==S::ok && m.callbacks==0,"exact massless moment with no quadrature");
  close(*m.rho_moment,exact); close(*m.pressure_moment,exact/3);
  require(m.rho_error_estimate>0 && m.pressure_error_estimate>0,"massless arithmetic is diagnosed");
  auto near=evaluate_thermal_moments(1e-8,p);
  require(near.status==S::ok,"near massless integration");
  close(*near.rho_moment,exact); close(*near.pressure_moment,exact/3);
  // Original analytic nonrelativistic leading terms; zeta values independently
  // published constants, not generated by the production quadrature.
  m=evaluate_thermal_moments(1e6,p);
  require(m.status==S::ok,"large mass ratio integration");
  close(*m.rho_moment/1e6L,1.8030853547393914281L);
  close(*m.pressure_moment*1e6L,7.7769581635752744475L);
  for (double mass:{0.,.0001,.06,100.}) {
    const ThermalSpecies s{mass,1.676e-4,2};
    const double a=.25, step=1e-4;
    const auto left=evaluate_thermal_species(s,a*std::exp(-step),p);
    const auto middle=evaluate_thermal_species(s,a,p);
    const auto right=evaluate_thermal_species(s,a*std::exp(step),p);
    require(left.status==S::ok && middle.status==S::ok && right.status==S::ok,"continuity states admitted");
    const long double derivative=(*right.rho_ev4-*left.rho_ev4)/(2*step);
    const long double expected=-3.L*(*middle.rho_ev4+*middle.pressure_ev4);
    require(std::abs(derivative-expected)<=4e-8L*std::abs(expected),"collisionless energy continuity");
    require(*middle.pressure_ev4<=*middle.rho_ev4/3*(1+1e-12),"pressure range");
    const auto doubled=evaluate_thermal_species({mass,1.676e-4,4},a,p);
    require(doubled.status==S::ok && *doubled.rho_ev4==2 * *middle.rho_ev4 &&
            *doubled.pressure_ev4==2 * *middle.pressure_ev4,"explicit state weight scaling");
  }
  ThermalFlatModel source{70,1,0,0,0,{}};
  auto background=prepare_thermal_background(source,p);
  require(background.status()==S::ok && *background.omega_lambda()==0,"radiation-only exact closure");
  const double scales[]{1,.5,.01};
  auto batch=background.evaluate(scales,thermal_e|thermal_h,p);
  require(batch.status==S::ok && batch.callbacks==0,"empty species analytic background");
  for (const auto &row:batch.rows) {
    close(*row.e.value,1.L/(row.scale_factor*row.scale_factor));
    close(*row.h_km_s_mpc.value,70.L/(row.scale_factor*row.scale_factor));
  }
  source={67.4,5.45e-5,3.7e-5,.0493,.264,{{.06,1.676e-4,2}}};
  background=prepare_thermal_background(source,p);
  require(background.status()==S::ok && background.preparation_callbacks()>0,"massive species retained normalization");
  require(*background.omega_species_today()>0 && *background.omega_lambda()>0,"species closure accounting");
  batch=background.evaluate(scales,thermal_e|thermal_h,p);
  require(batch.status==S::ok,"massive background batch");
  require(*batch.rows[0].e.value==1 && *batch.rows[0].h_km_s_mpc.value==67.4 &&
          batch.rows[0].callbacks==0,"present normalization retained exactly");
  std::size_t callbacks=0;
  for (const auto &row:batch.rows) {
    require(row.e.status==S::ok && row.h_km_s_mpc.status==S::ok,"background outputs accepted");
    close(*row.h_km_s_mpc.value,67.4L * *row.e.value);
    callbacks+=row.callbacks;
  }
  require(callbacks==batch.callbacks,"background callback accounting");
  static_assert(std::is_nothrow_move_constructible_v<ThermalBackground>);
  static_assert(std::is_nothrow_move_assignable_v<ThermalBackground>);
  {
    const ThermalFlatModel life_model{70,5e-5,2e-5,.05,.25,{{.06,.000168,2}}};
    const double life_scale[]{.1};
    auto original=prepare_thermal_background(life_model,p);
    const auto expected=original.evaluate(life_scale,thermal_e|thermal_h,p);
    require(expected.rows[0].e.status==S::ok,"move witness initial model accepted");
    close(*expected.rows[0].e.value,17.39871883575367278847808L);
    const auto normalization=original.omega_species_today();
    const auto preparation_callbacks=original.preparation_callbacks();
    auto copy=original;
    auto moved=std::move(original);
    auto source_refused=[&](const ThermalBackground &owner) {
      require(owner.status()==S::invalid_input && owner.source().species.empty() &&
              !owner.omega_species_today() && !owner.omega_lambda() &&
              owner.preparation_callbacks()==0,"moved source is an invalid physical owner");
      const auto result=owner.evaluate(life_scale,thermal_e|thermal_h,p);
      require(result.status==S::invalid_input && result.rows.empty() &&
              result.callbacks==0,"moved source returns no calculation payload");
    };
    auto retained=[&](const ThermalBackground &owner) {
      require(owner.status()==S::ok && owner.source().species.size()==1 &&
              owner.source().species[0].mass_ev==.06 &&
              owner.omega_species_today()==normalization &&
              owner.preparation_callbacks()==preparation_callbacks,
              "move target retains the complete physical identity");
      const auto result=owner.evaluate(life_scale,thermal_e|thermal_h,p);
      require(result.rows.size()==1 && result.rows[0].e.status==S::ok &&
              result.rows[0].h_km_s_mpc.status==S::ok &&
              result.rows[0].e.value==expected.rows[0].e.value &&
              result.rows[0].h_km_s_mpc.value==expected.rows[0].h_km_s_mpc.value,
              "owner lifetime preserves expansion");
    };
    source_refused(original); retained(moved); retained(copy);
    auto assigned=prepare_thermal_background({70,1,0,0,0,{}},p);
    assigned=std::move(moved);
    source_refused(moved); retained(assigned);
    auto *self_alias=&assigned;
    // Use an alias so intentional self move remains portable under warnings.
    assigned=std::move(*self_alias);
    retained(assigned);
    ThermalBackground copied;
    copied=copy;
    retained(copied);
    copy=ThermalBackground{};
    retained(copied);
  }
  auto q=p; q.maximum_total_callbacks=0;
  batch=background.evaluate(scales,thermal_e,q);
  require(batch.rows[0].e.status==S::ok && batch.rows[1].e.status==S::work_limit &&
          batch.rows[1].callbacks==0,"present normalization survives exhausted moment work");
  require(!batch.rows[0].h_km_s_mpc.value,"unrequested H omitted");
  q=p; q.maximum_callbacks_per_evaluation=7;
  m=evaluate_thermal_moments(1,q);
  require(m.status==S::work_limit && m.callbacks<=7 && !m.rho_moment,"failed quadrature has no fabricated output");
  q=p; q.maximum_total_callbacks=13;
  require(prepare_thermal_background(source,q).preparation_callbacks()<=13,"preparation global work bound");
  q=p; q.maximum_points=0;
  require(background.evaluate(scales,thermal_e,q).status==S::work_limit,"point quota precedes rows");
  q=p; q.maximum_native_bytes=0;
  require(prepare_thermal_background(source,q).status()==S::work_limit,"preparation payload admission");
  require(background.evaluate(scales,thermal_e,q).rows.empty(),"batch payload admission");
  q=p; q.maximum_species=0;
  require(prepare_thermal_background(source,q).status()==S::work_limit,"species quota");
  q=p; q.absolute_tolerance=1e-30; q.relative_tolerance=1e-30;
  require(evaluate_thermal_moments(1,q).status==S::conditioning_budget_exceeded,"unattainable tolerance refused");
  q=p; q.maximum_depth=61;
  require(evaluate_thermal_moments(1,q).status==S::invalid_input,"invalid depth");
  q=p; q.absolute_tolerance=0; q.relative_tolerance=0;
  require(evaluate_thermal_moments(0,q).status==S::invalid_input,"zero budget refused even for massless");
  const double inf=std::numeric_limits<double>::infinity(), nan=std::numeric_limits<double>::quiet_NaN();
  for (double y:{inf,nan}) require(evaluate_thermal_moments(y,p).status==S::nonfinite_input,"nonfinite moment input");
  require(evaluate_thermal_moments(-1,p).status==S::outside_domain,"negative mass ratio");
  for (const auto &s:std::array<ThermalSpecies,4>{{{-1,1,1},{1,0,1},{1,1,0},{nan,1,1}}})
    require(evaluate_thermal_species(s,.5,p).status!=S::ok,"invalid species");
  for (double a:{0.,-1.,1.01,inf,nan})
    require(evaluate_thermal_species(source.species[0],a,p).status!=S::ok,"invalid scale factor");
  source={70,1,std::numeric_limits<double>::denorm_min(),0,0,{}};
  require(prepare_thermal_background(source,p).status()==S::outside_domain,"strict tiny closure excess");
  source={70,0,0,.5,.5,{{0,1e-100,2}}};
  require(prepare_thermal_background(source,p).status()==S::outside_domain,"tiny positive species excess after matter closure");
  source={70,-1,0,0,0,{}};
  require(prepare_thermal_background(source,p).status()==S::outside_domain,"negative component");
  source={70,0,0,0,0,std::vector<ThermalSpecies>(17,{0,1e-4,2})};
  require(prepare_thermal_background(source,p).status()==S::invalid_input,"hard small-species domain");
  require(evaluate_thermal_species({0,1e-100,2},1,p).status==S::outside_domain,"positive density underflow refused");
  require(evaluate_thermal_species({0,1e100,2},1,p).status==S::outside_domain,"density overflow refused");
  source={std::numeric_limits<double>::max(),1,0,0,0,{}};
  background=prepare_thermal_background(source,p);
  require(background.status()==S::ok,"dimensional overflow is deferred to output");
  batch=background.evaluate(scales,thermal_e|thermal_h,p);
  require(batch.rows[1].e.status==S::ok && batch.rows[1].h_km_s_mpc.status==S::outside_domain,
          "dimensionless E survives H overflow");
  const double tiny[]{std::numeric_limits<double>::denorm_min()};
  batch=background.evaluate(tiny,thermal_e,p);
  require(batch.rows[0].e.status==S::outside_domain,"positive E overflow refused");
  require(background.evaluate(scales,4,p).status==S::invalid_input,"unknown requested output refused");
  const int original=std::fegetround(); std::fesetround(FE_UPWARD);
  m=evaluate_thermal_moments(0,p);
  batch=background.evaluate(scales,thermal_e,p);
  std::fesetround(original);
  require(m.status==S::invalid_input && batch.rows.empty(),"unsupported rounding rejected");
  std::cout << "thermal_neutrino owner checks=" << checks << '\n';
}
