// Generated by tools/generate_abi.py; edit schema/abi.json.
#pragma once
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
#define COSMO_ABI_VERSION 1u
#define COSMO_OK 0u
#define COSMO_ABI_MISMATCH 1u
#define COSMO_INVALID_INPUT 2u
#define COSMO_OVERFLOW 3u
#define COSMO_ALLOCATION_FAILURE 4u
#define COSMO_EXCEPTION 5u
typedef struct cosmo_result cosmo_result;
typedef struct { uint32_t struct_size, abi_version, element_type, reserved; const int64_t *data; uint64_t length, byte_length; } cosmo_i64_buffer;
uint32_t cosmo_add(const cosmo_i64_buffer*, const cosmo_i64_buffer*, uint32_t fault, cosmo_result**);
uint32_t cosmo_result_view(const cosmo_result*, const int64_t**, uint64_t*);
uint32_t cosmo_result_destroy(cosmo_result*);
#ifdef __cplusplus
}
#endif
