target_sources(irred_core PRIVATE src/curved_flrw.cpp)
add_executable(test_curved_flrw tests/test_curved_flrw.cpp)
target_link_libraries(test_curved_flrw PRIVATE irred_core)
target_compile_options(test_curved_flrw PRIVATE -Wall -Wextra -Wpedantic -fno-fast-math -ffp-contract=off)
add_test(NAME curved_flrw_contract COMMAND test_curved_flrw)
add_executable(test_curved_flrw_sdk tests/test_curved_flrw_sdk.cpp)
target_link_libraries(test_curved_flrw_sdk PRIVATE irred_core)
target_compile_options(test_curved_flrw_sdk PRIVATE -Wall -Wextra -Wpedantic -fno-fast-math -ffp-contract=off)
add_test(NAME curved_flrw_sdk_contract COMMAND test_curved_flrw_sdk)
