target_sources(irred_core PRIVATE src/dgp_growth.cpp)
add_executable(test_dgp_growth tests/test_dgp_growth.cpp)
target_link_libraries(test_dgp_growth PRIVATE irred_core)
target_compile_options(test_dgp_growth PRIVATE -Wall -Wextra -Wpedantic -fno-fast-math -ffp-contract=off)
add_test(NAME dgp_growth_contract COMMAND test_dgp_growth)
add_executable(test_dgp_growth_installed tests/test_dgp_growth_installed.cpp)
target_link_libraries(test_dgp_growth_installed PRIVATE irred_core)
target_compile_options(test_dgp_growth_installed PRIVATE -Wall -Wextra -Wpedantic -fno-fast-math -ffp-contract=off)
add_test(NAME dgp_growth_installed_contract COMMAND test_dgp_growth_installed)
