target_sources(irred_core PRIVATE src/hernquist_sphere.cpp)
add_executable(test_hernquist_sphere tests/test_hernquist_sphere.cpp)
target_link_libraries(test_hernquist_sphere PRIVATE irred_core)
target_compile_options(test_hernquist_sphere PRIVATE -Wall -Wextra -Wpedantic -fno-fast-math -ffp-contract=off)
add_test(NAME hernquist_sphere_contract COMMAND test_hernquist_sphere)
add_executable(test_hernquist_sphere_installed tests/test_hernquist_sphere_installed.cpp)
target_link_libraries(test_hernquist_sphere_installed PRIVATE irred_core)
target_compile_options(test_hernquist_sphere_installed PRIVATE -Wall -Wextra -Wpedantic -fno-fast-math -ffp-contract=off)
add_test(NAME hernquist_sphere_installed_contract COMMAND test_hernquist_sphere_installed)
