target_sources(irred_core PRIVATE src/nfw_halo.cpp)
add_executable(test_nfw_halo tests/test_nfw_halo.cpp)
target_link_libraries(test_nfw_halo PRIVATE irred_core)
target_compile_options(test_nfw_halo PRIVATE -Wall -Wextra -Wpedantic -fno-fast-math -ffp-contract=off)
add_test(NAME nfw_halo_contract COMMAND test_nfw_halo)
add_executable(test_nfw_halo_installed tests/test_nfw_halo_installed.cpp)
target_link_libraries(test_nfw_halo_installed PRIVATE irred_core)
target_compile_options(test_nfw_halo_installed PRIVATE -Wall -Wextra -Wpedantic -fno-fast-math -ffp-contract=off)
add_test(NAME nfw_halo_installed_contract COMMAND test_nfw_halo_installed)
