target_sources(irred_core PRIVATE src/plummer_sphere.cpp)
add_executable(test_plummer_sphere tests/test_plummer_sphere.cpp)
target_link_libraries(test_plummer_sphere PRIVATE irred_core)
target_compile_options(test_plummer_sphere PRIVATE -Wall -Wextra -Wpedantic -fno-fast-math -ffp-contract=off)
add_test(NAME plummer_sphere_contract COMMAND test_plummer_sphere)
add_executable(test_plummer_sphere_installed tests/test_plummer_sphere_installed.cpp)
target_link_libraries(test_plummer_sphere_installed PRIVATE irred_core)
target_compile_options(test_plummer_sphere_installed PRIVATE -Wall -Wextra -Wpedantic -fno-fast-math -ffp-contract=off)
add_test(NAME plummer_sphere_installed_contract COMMAND test_plummer_sphere_installed)
