#!/usr/bin/env python3
import json,pathlib
root=pathlib.Path(__file__).resolve().parents[1]
s=json.loads((root/'schema/abi.json').read_text())
status='\n'.join(f'#define COSMO_{k} {v}u' for k,v in s['statuses'].items())
(root/'cpp/include/cosmology/abi.h').write_text('''// Generated by tools/generate_abi.py; edit schema/abi.json.
#pragma once
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
#define COSMO_ABI_VERSION '''+str(s['abi_version'])+'u\n'+status+'''
typedef struct cosmo_result cosmo_result;
typedef struct { uint32_t struct_size, abi_version, element_type, reserved; const int64_t *data; uint64_t length, byte_length; } cosmo_i64_buffer;
uint32_t cosmo_add(const cosmo_i64_buffer*, const cosmo_i64_buffer*, uint32_t fault, cosmo_result**);
uint32_t cosmo_result_view(const cosmo_result*, const int64_t**, uint64_t*);
uint32_t cosmo_result_destroy(cosmo_result*);
#ifdef __cplusplus
}
#endif
''')
(root/'src/abi_generated.rs').write_text('// Generated by tools/generate_abi.py; edit schema/abi.json.\n'+f'pub const ABI_VERSION:u32={s["abi_version"]};\n'+''.join(f'pub const {k}:u32={v};\n' for k,v in s['statuses'].items())+'''#[repr(C)]
pub struct Buffer { pub struct_size:u32, pub abi_version:u32, pub element_type:u32, pub reserved:u32, pub data:*const i64, pub length:u64, pub byte_length:u64 }
unsafe extern "C" {
pub fn cosmo_add(a:*const Buffer,b:*const Buffer,fault:u32,out:*mut *mut std::ffi::c_void)->u32;
pub fn cosmo_result_view(r:*const std::ffi::c_void,data:*mut *const i64,n:*mut u64)->u32;
pub fn cosmo_result_destroy(r:*mut std::ffi::c_void)->u32;
}
''')

import subprocess
subprocess.run(['rustfmt',str(root/'src/abi_generated.rs')],check=True)
