#!/usr/bin/env python3
"""Generate both languages from one versioned structural schema; no science algebra."""
import json,pathlib,re,subprocess
root=pathlib.Path(__file__).resolve().parents[1]
s=json.loads((root/'schema/abi.json').read_text())
types={'u32':('uint32_t','u32'),'u64':('uint64_t','u64'),'const_i64_ptr':('const int64_t*','*const i64'),'const_f64_ptr':('const double*','*const f64'),'const_i64_out':('const int64_t**','*mut *const i64'),'const_f64_out':('const double**','*mut *const f64'),'const_u32_out':('const uint32_t**','*mut *const u32'),'const_u64_out':('const uint64_t**','*mut *const u64'),'u64_ptr':('uint64_t*','*mut u64'),'result':('cosmo_result*','*mut std::ffi::c_void'),'const_result':('const cosmo_result*','*const std::ffi::c_void'),'result_out':('cosmo_result**','*mut *mut std::ffi::c_void')}
types.update({'const_u8_ptr':('const uint8_t*','*const u8'),'const_u64_ptr':('const uint64_t*','*const u64'),'u32_ptr':('uint32_t*','*mut u32'),'const_u8_out':('const uint8_t**','*mut *const u8'),'prepared':('cosmo_prepared*','*mut std::ffi::c_void'),'const_prepared':('const cosmo_prepared*','*const std::ffi::c_void'),'prepared_out':('cosmo_prepared**','*mut *mut std::ffi::c_void')})
types.update({'f64':('double','f64'),'gaussian':('cosmo_gaussian*','*mut std::ffi::c_void'),'const_gaussian':('const cosmo_gaussian*','*const std::ffi::c_void'),'gaussian_out':('cosmo_gaussian**','*mut *mut std::ffi::c_void'),'gaussian_result':('cosmo_gaussian_result*','*mut std::ffi::c_void'),'const_gaussian_result':('const cosmo_gaussian_result*','*const std::ffi::c_void'),'gaussian_result_out':('cosmo_gaussian_result**','*mut *mut std::ffi::c_void'),'const_gaussian_row_out':('const cosmo_gaussian_row**','*mut *const GaussianRow')})
for structure in s['structures']:
 types[structure['rust_name']]=(structure['c_name'],structure['rust_name'])
 types[structure['rust_name']+'_ptr']=(structure['c_name']+'*','*mut '+structure['rust_name'])
 types['const_'+structure['rust_name']+'_ptr']=('const '+structure['c_name']+'*','*const '+structure['rust_name'])
for name,c_name in s.get('opaque_types',{}).items():
 types[name]=(c_name+'*','*mut std::ffi::c_void')
 types['const_'+name]=('const '+c_name+'*','*const std::ffi::c_void')
 types[name+'_out']=(c_name+'**','*mut *mut std::ffi::c_void')
for structure in s['structures']:
 types['const_'+structure['rust_name']+'_out']=('const '+structure['c_name']+'**','*mut *const '+structure['rust_name'])
def macro(name):return re.sub('[^A-Za-z0-9_]','_',name).upper()
c=['// Generated by tools/generate_abi.py; edit schema/abi.json.','#pragma once','#include <stdint.h>','#ifdef __cplusplus','extern "C" {','#endif',f'#define COSMO_ABI_VERSION {s["abi_version"]}u','typedef struct cosmo_result cosmo_result;','typedef struct cosmo_prepared cosmo_prepared;','typedef struct cosmo_gaussian cosmo_gaussian;','typedef struct cosmo_gaussian_result cosmo_gaussian_result;']
c.extend('typedef struct '+value+' '+value+';' for value in s.get('opaque_types',{}).values())
r=['// Generated by tools/generate_abi.py; edit schema/abi.json.',f'pub const ABI_VERSION:u32={s["abi_version"]};']
for name,value in s['statuses'].items():
 c.append(f'#define COSMO_{name} {value}u');r.append(f'pub const {name}:u32={value};')
for group,tags in s['quantity_tags'].items():
 for name,value in tags.items():c.append(f'#define COSMO_{macro(group)}_{macro(name)} {value}u')
c.append(f'#define COSMO_MAX_BATCH_ELEMENTS {s["max_batch_elements"]}u')
r.append(f'pub const MAX_BATCH_ELEMENTS:u64={s["max_batch_elements"]};')
for group,tags in s['numerical_tags'].items():
 for name,value in tags.items():c.append(f'#define COSMO_NUMERICAL_{macro(group)}_{macro(name)} {value}u')
for group,tags in s.get('observation_tags',{}).items():
 for name,value in tags.items():
  c.append(f'#define COSMO_OBSERVATION_{macro(group)}_{macro(name)} {value}u')
  r.append(f'pub const OBSERVATION_{macro(group)}_{macro(name)}:u32={value};')
for group,tags in s.get('gaussian_tags',{}).items():
 for name,value in tags.items():
  c.append(f'#define COSMO_GAUSSIAN_{macro(group)}_{macro(name)} {value}u')
  r.append(f'pub const GAUSSIAN_{macro(group)}_{macro(name)}:u32={value};')
r.append("pub fn gaussian_status_name(value:u32)->Option<&'static str>{match value {")
for name,value in s['gaussian_tags']['status'].items():r.append(f'{value}=>Some("{name}"),')
r.append('_=>None,}}')
for group,tags in s.get('supernova_tags',{}).items():
 for name,value in tags.items():
  c.append(f'#define COSMO_SUPERNOVA_{macro(group)}_{macro(name)} {value}u')
  r.append(f'pub const SUPERNOVA_{macro(group)}_{macro(name)}:u32={value};')
r.append("pub fn supernova_tag_id(group:&str,label:&str)->Option<u32>{match(group,label){")
for group,tags in s.get('supernova_tags',{}).items():
 for name,value in tags.items():r.append(f'("{group}","{name}")=>Some({value}),')
r.append('_=>None,}}')
r.append("pub fn supernova_status_name(value:u32)->Option<&'static str>{match value {")
for name,value in s.get('supernova_tags',{}).get('status',{}).items():r.append(f'{value}=>Some("{name}"),')
r.append('_=>None,}}')
for group,tags in s.get('piecewise_tags',{}).items():
 for name,value in tags.items():
  c.append(f'#define COSMO_PIECEWISE_{macro(group)}_{macro(name)} {value}u')
  r.append(f'pub const PIECEWISE_{macro(group)}_{macro(name)}:u32={value};')
r.append("pub fn piecewise_tag_name(group:&str,value:u32)->Option<&'static str>{match(group,value){")
for group,tags in s.get('piecewise_tags',{}).items():
 for name,value in tags.items():r.append(f'("{group}",{value})=>Some("{name}"),')
r.append('_=>None,}}')
for group,tags in s.get('bao_tags',{}).items():
 for name,value in tags.items():
  c.append(f'#define COSMO_BAO_{macro(group)}_{macro(name)} {value}u')
  r.append(f'pub const BAO_{macro(group)}_{macro(name)}:u32={value};')
r.append("pub fn bao_tag_id(group:&str,label:&str)->Option<u32>{match(group,label){")
for group,tags in s.get('bao_tags',{}).items():
 for name,value in tags.items():r.append(f'("{group}","{name}")=>Some({value}),')
r.append('_=>None,}}')
for group,tags in s.get('background_v2_tags',{}).items():
 for name,value in tags.items():
  c.append(f'#define COSMO_BACKGROUND_V2_{macro(group)}_{macro(name)} {value}u')
  r.append(f'pub const BACKGROUND_V2_{macro(group)}_{macro(name)}:u32={value};')
r.append("pub fn background_v2_tag_id(group:&str,label:&str)->Option<u32>{match(group,label){")
for group,tags in s.get('background_v2_tags',{}).items():
 for name,value in tags.items():r.append(f'("{group}","{name}")=>Some({value}),')
r.append('_=>None,}}')
for group,tags in s.get('background_tags',{}).items():
 for name,value in tags.items():
  c.append(f'#define COSMO_BACKGROUND_{macro(group)}_{macro(name)} {value}u')
  r.append(f'pub const BACKGROUND_{macro(group)}_{macro(name)}:u32={value};')
r.append("pub fn background_tag_id(group:&str,label:&str)->Option<u32>{match(group,label){")
for group,tags in s['background_tags'].items():
 for name,value in tags.items():r.append(f'("{group}","{name}")=>Some({value}),')
r.append('_=>None,}}')
r.append("pub fn background_status_name(value:u32)->Option<&'static str>{match value {")
for name,value in s['background_tags']['status'].items():r.append(f'{value}=>Some("{name}"),')
r.append('_=>None,}}')
for group,tags in s.get('expansion_tags',{}).items():
 for name,value in tags.items():
  c.append(f'#define COSMO_EXPANSION_{macro(group)}_{macro(name)} {value}u')
  r.append(f'pub const EXPANSION_{macro(group)}_{macro(name)}:u32={value};')
r.append("pub fn expansion_tag_name(group:&str,value:u32)->Option<&'static str>{match(group,value){")
for group,tags in s.get('expansion_tags',{}).items():
 for name,value in tags.items():r.append(f'(\"{group}\",{value})=>Some(\"{name}\"),')
r.append('_=>None,}}')
for structure in s['structures']:
 c.append('typedef struct { '+' '.join(f'{types[t][0]} {n};' for n,t in structure['fields'])+' } '+structure['c_name']+';')
 r.append('#[allow(non_snake_case)]\n#[repr(C)]\npub struct '+structure['rust_name']+' { '+', '.join(f'pub {n}:{types[t][1]}' for n,t in structure['fields'])+' }')
r.append('unsafe extern "C" {')
for function in s['functions']:
 c.append('uint32_t '+function['name']+'('+', '.join(types[t][0]+' '+n for n,t in function['args'])+');')
 r.append('pub fn '+function['name']+'('+', '.join(n+':'+types[t][1] for n,t in function['args'])+')->u32;')
r.append('}')
r.append('#[derive(Clone,serde::Deserialize,serde::Serialize)]\n#[serde(deny_unknown_fields)]\npub struct MetadataFields { '+', '.join('pub '+group+':String' for group in s['quantity_tags'] if group!='quantity_status')+' }')
r.append('pub fn tag_id(group:&str,label:&str)->Option<u32> { match (group,label) {')
for group,tags in s['quantity_tags'].items():
 for name,value in tags.items():r.append(f'("{group}","{name}")=>Some({value}),')
r.append('_=>None,}}')
r.append('pub fn quantity_status_name(value:u32)->Option<&\'static str> {match value {')
for name,value in s['quantity_tags']['quantity_status'].items():r.append(f'{value}=>Some("{name}"),')
r.append('_=>None,}}')
r.append('#[derive(Clone,serde::Deserialize,serde::Serialize)]\n#[serde(deny_unknown_fields)]\npub struct ObservationMetadataFields { '+', '.join('pub '+g+':String' for g in s['observation_tags'] if g not in ['selection','status'])+' }')
r.append('pub fn observation_tag_id(group:&str,label:&str)->Option<u32> {match(group,label){')
for group,tags in s['observation_tags'].items():
 for name,value in tags.items():r.append(f'("{group}","{name}")=>Some({value}),')
r.append('_=>None,}}')
r.append('pub fn observation_status_name(value:u32)->Option<&\'static str>{match value {')
for name,value in s['observation_tags']['status'].items():r.append(f'{value}=>Some("{name}"),')
r.append('_=>None,}}')
r.append('pub fn numerical_operation_id(label:&str)->Option<u32> {match label {')
for name,value in s['numerical_tags']['operation'].items():r.append(f'"{name}"=>Some({value}),')
r.append('_=>None,}}')
r.append('pub fn numerical_status_name(value:u32)->Option<&\'static str> {match value {')
for name,value in s['numerical_tags']['status'].items():r.append(f'{value}=>Some("{name}"),')
r.append('_=>None,}}')
r.append('pub fn numerical_output_length(method:&str,input:usize)->Option<usize> {match method {')
for name,shape in s['numerical_output_shapes'].items():r.append(f'"{name}"=>Some('+('1' if shape=='scalar' else 'input')+'),')
r.append('_=>None,}}')
c.append('static inline uint64_t cosmo_numerics_output_length(uint32_t operation,uint64_t input) {switch(operation) {')
for name,shape in s['numerical_output_shapes'].items():c.append(f'case COSMO_NUMERICAL_OPERATION_{macro(name)}:return '+('1' if shape=='scalar' else 'input')+';')
c.append('default:return UINT64_MAX;}}')
c+=['#ifdef __cplusplus','}','#endif']
(root/'cpp/include/irred/abi.h').write_text('\n'.join(c)+'\n');(root/'src/abi_generated.rs').write_text('\n'.join(r)+'\n')
checks=[]
for group,enum in [('unit','Unit'),('role','Role'),('frame','Frame'),('convention','LengthConvention'),('quantity_status','QuantityStatus')]:
 for name in s['quantity_tags'][group]:checks.append(f'static_assert(static_cast<uint32_t>(irred::{enum}::{name}) == COSMO_{macro(group)}_{macro(name)});')
for name in s['numerical_tags']['status']:checks.append(f'static_assert(static_cast<uint32_t>(irred::numerics::Status::{name}) == COSMO_NUMERICAL_STATUS_{macro(name)});')
(root/'cpp/include/irred/quantity_enum_checks.inc').write_text('// Generated structural ID agreement; physical semantics owned by quantities.cpp.\n'+'\n'.join(checks)+'\n')
observation_checks=[]
for group,enum in [('profile','Profile'),('role','Role'),('unit','Unit'),('calibration','Calibration'),('uncertainty','Uncertainty'),('uncertainty_unit','UncertaintyUnit'),('component','Component'),('selection','Selection'),('status','Status')]:
 for name in s.get('observation_tags',{}).get(group,{}):
  observation_checks.append(f'static_assert(static_cast<uint32_t>(irred::observations::{enum}::{name}) == COSMO_OBSERVATION_{macro(group)}_{macro(name)});')
(root/'cpp/include/irred/observation_enum_checks.inc').write_text('// Generated structural observation tag agreement.\n'+'\n'.join(observation_checks)+'\n')
subprocess.run(['rustfmt',str(root/'src/abi_generated.rs')],check=True)

# Agent-facing current requests use the same structural tags and one schema.
from current_run_schema import build_schema
run_path=root/'schema/run.schema.json'
existing=json.loads(run_path.read_text())
fixture=existing.get('$defs',{}).get('fixture',existing)
run_path.write_text(json.dumps(build_schema(s,fixture),indent=2)+'\n')
