#!/usr/bin/env python3
"""Generate both languages from one versioned structural schema; no science algebra."""
import json,pathlib,re,subprocess
root=pathlib.Path(__file__).resolve().parents[1]
s=json.loads((root/'schema/abi.json').read_text())
types={'u32':('uint32_t','u32'),'u64':('uint64_t','u64'),'const_i64_ptr':('const int64_t*','*const i64'),'const_f64_ptr':('const double*','*const f64'),'const_i64_out':('const int64_t**','*mut *const i64'),'const_f64_out':('const double**','*mut *const f64'),'const_u32_out':('const uint32_t**','*mut *const u32'),'const_u64_out':('const uint64_t**','*mut *const u64'),'u64_ptr':('uint64_t*','*mut u64'),'result':('cosmo_result*','*mut std::ffi::c_void'),'const_result':('const cosmo_result*','*const std::ffi::c_void'),'result_out':('cosmo_result**','*mut *mut std::ffi::c_void')}
types.update({'const_u8_ptr':('const uint8_t*','*const u8'),'const_u64_ptr':('const uint64_t*','*const u64'),'u32_ptr':('uint32_t*','*mut u32'),'const_u8_out':('const uint8_t**','*mut *const u8'),'prepared':('cosmo_prepared*','*mut std::ffi::c_void'),'const_prepared':('const cosmo_prepared*','*const std::ffi::c_void'),'prepared_out':('cosmo_prepared**','*mut *mut std::ffi::c_void')})
types.update({'f64':('double','f64'),'gaussian':('cosmo_gaussian*','*mut std::ffi::c_void'),'const_gaussian':('const cosmo_gaussian*','*const std::ffi::c_void'),'gaussian_out':('cosmo_gaussian**','*mut *mut std::ffi::c_void'),'gaussian_result':('cosmo_gaussian_result*','*mut std::ffi::c_void'),'const_gaussian_result':('const cosmo_gaussian_result*','*const std::ffi::c_void'),'gaussian_result_out':('cosmo_gaussian_result**','*mut *mut std::ffi::c_void'),'const_gaussian_row_out':('const cosmo_gaussian_row**','*mut *const GaussianRow')})
types.update({'background_result':('cosmo_background_result*','*mut std::ffi::c_void'),'const_background_result':('const cosmo_background_result*','*const std::ffi::c_void'),'background_result_out':('cosmo_background_result**','*mut *mut std::ffi::c_void'),'const_background_slot_out':('const cosmo_background_slot**','*mut *const BackgroundSlot')})
types.update({'supernova':('cosmo_supernova*','*mut std::ffi::c_void'),'const_supernova':('const cosmo_supernova*','*const std::ffi::c_void'),'supernova_out':('cosmo_supernova**','*mut *mut std::ffi::c_void'),'supernova_result':('cosmo_supernova_result*','*mut std::ffi::c_void'),'const_supernova_result':('const cosmo_supernova_result*','*const std::ffi::c_void'),'supernova_result_out':('cosmo_supernova_result**','*mut *mut std::ffi::c_void'),'const_supernova_slot_out':('const cosmo_supernova_slot**','*mut *const SupernovaSlot')})
for structure in s['structures']:
 types[structure['rust_name']]=(structure['c_name'],structure['rust_name'])
 types[structure['rust_name']+'_ptr']=(structure['c_name']+'*','*mut '+structure['rust_name'])
 types['const_'+structure['rust_name']+'_ptr']=('const '+structure['c_name']+'*','*const '+structure['rust_name'])
def macro(name):return re.sub('[^A-Za-z0-9_]','_',name).upper()
c=['// Generated by tools/generate_abi.py; edit schema/abi.json.','#pragma once','#include <stdint.h>','#ifdef __cplusplus','extern "C" {','#endif',f'#define COSMO_ABI_VERSION {s["abi_version"]}u','typedef struct cosmo_result cosmo_result;','typedef struct cosmo_prepared cosmo_prepared;','typedef struct cosmo_gaussian cosmo_gaussian;','typedef struct cosmo_gaussian_result cosmo_gaussian_result;','typedef struct cosmo_background_result cosmo_background_result;','typedef struct cosmo_supernova cosmo_supernova;','typedef struct cosmo_supernova_result cosmo_supernova_result;']
r=['// Generated by tools/generate_abi.py; edit schema/abi.json.',f'pub const ABI_VERSION:u32={s["abi_version"]};']
for name,value in s['statuses'].items():
 c.append(f'#define COSMO_{name} {value}u');r.append(f'pub const {name}:u32={value};')
for group,tags in s['quantity_tags'].items():
 for name,value in tags.items():c.append(f'#define COSMO_{macro(group)}_{macro(name)} {value}u')
c.append(f'#define COSMO_MAX_BATCH_ELEMENTS {s["max_batch_elements"]}u')
r.append(f'pub const MAX_BATCH_ELEMENTS:u64={s["max_batch_elements"]};')
for group,tags in s['numerical_tags'].items():
 for name,value in tags.items():c.append(f'#define COSMO_NUMERICAL_{macro(group)}_{macro(name)} {value}u')
for group,tags in s.get('observation_tags',{}).items():
 for name,value in tags.items():
  c.append(f'#define COSMO_OBSERVATION_{macro(group)}_{macro(name)} {value}u')
  r.append(f'pub const OBSERVATION_{macro(group)}_{macro(name)}:u32={value};')
for group,tags in s.get('gaussian_tags',{}).items():
 for name,value in tags.items():
  c.append(f'#define COSMO_GAUSSIAN_{macro(group)}_{macro(name)} {value}u')
  r.append(f'pub const GAUSSIAN_{macro(group)}_{macro(name)}:u32={value};')
r.append("pub fn gaussian_status_name(value:u32)->Option<&'static str>{match value {")
for name,value in s['gaussian_tags']['status'].items():r.append(f'{value}=>Some("{name}"),')
r.append('_=>None,}}')
for group,tags in s.get('supernova_tags',{}).items():
 for name,value in tags.items():
  c.append(f'#define COSMO_SUPERNOVA_{macro(group)}_{macro(name)} {value}u')
  r.append(f'pub const SUPERNOVA_{macro(group)}_{macro(name)}:u32={value};')
r.append("pub fn supernova_tag_id(group:&str,label:&str)->Option<u32>{match(group,label){")
for group,tags in s.get('supernova_tags',{}).items():
 for name,value in tags.items():r.append(f'("{group}","{name}")=>Some({value}),')
r.append('_=>None,}}')
r.append("pub fn supernova_status_name(value:u32)->Option<&'static str>{match value {")
for name,value in s.get('supernova_tags',{}).get('status',{}).items():r.append(f'{value}=>Some("{name}"),')
r.append('_=>None,}}')
for group,tags in s.get('background_tags',{}).items():
 for name,value in tags.items():
  c.append(f'#define COSMO_BACKGROUND_{macro(group)}_{macro(name)} {value}u')
  r.append(f'pub const BACKGROUND_{macro(group)}_{macro(name)}:u32={value};')
r.append("pub fn background_tag_id(group:&str,label:&str)->Option<u32>{match(group,label){")
for group,tags in s['background_tags'].items():
 for name,value in tags.items():r.append(f'("{group}","{name}")=>Some({value}),')
r.append('_=>None,}}')
r.append("pub fn background_status_name(value:u32)->Option<&'static str>{match value {")
for name,value in s['background_tags']['status'].items():r.append(f'{value}=>Some("{name}"),')
r.append('_=>None,}}')
for structure in s['structures']:
 c.append('typedef struct { '+' '.join(f'{types[t][0]} {n};' for n,t in structure['fields'])+' } '+structure['c_name']+';')
 r.append('#[repr(C)]\npub struct '+structure['rust_name']+' { '+', '.join(f'pub {n}:{types[t][1]}' for n,t in structure['fields'])+' }')
r.append('unsafe extern "C" {')
for function in s['functions']:
 c.append('uint32_t '+function['name']+'('+', '.join(types[t][0]+' '+n for n,t in function['args'])+');')
 r.append('pub fn '+function['name']+'('+', '.join(n+':'+types[t][1] for n,t in function['args'])+')->u32;')
r.append('}')
r.append('#[derive(Clone,serde::Deserialize,serde::Serialize)]\n#[serde(deny_unknown_fields)]\npub struct MetadataFields { '+', '.join('pub '+group+':String' for group in s['quantity_tags'] if group!='quantity_status')+' }')
r.append('pub fn tag_id(group:&str,label:&str)->Option<u32> { match (group,label) {')
for group,tags in s['quantity_tags'].items():
 for name,value in tags.items():r.append(f'("{group}","{name}")=>Some({value}),')
r.append('_=>None,}}')
r.append('pub fn quantity_status_name(value:u32)->Option<&\'static str> {match value {')
for name,value in s['quantity_tags']['quantity_status'].items():r.append(f'{value}=>Some("{name}"),')
r.append('_=>None,}}')
r.append('#[derive(Clone,serde::Deserialize,serde::Serialize)]\n#[serde(deny_unknown_fields)]\npub struct ObservationMetadataFields { '+', '.join('pub '+g+':String' for g in s['observation_tags'] if g not in ['selection','status'])+' }')
r.append('pub fn observation_tag_id(group:&str,label:&str)->Option<u32> {match(group,label){')
for group,tags in s['observation_tags'].items():
 for name,value in tags.items():r.append(f'("{group}","{name}")=>Some({value}),')
r.append('_=>None,}}')
r.append('pub fn observation_status_name(value:u32)->Option<&\'static str>{match value {')
for name,value in s['observation_tags']['status'].items():r.append(f'{value}=>Some("{name}"),')
r.append('_=>None,}}')
r.append('pub fn numerical_operation_id(label:&str)->Option<u32> {match label {')
for name,value in s['numerical_tags']['operation'].items():r.append(f'"{name}"=>Some({value}),')
r.append('_=>None,}}')
r.append('pub fn numerical_status_name(value:u32)->Option<&\'static str> {match value {')
for name,value in s['numerical_tags']['status'].items():r.append(f'{value}=>Some("{name}"),')
r.append('_=>None,}}')
r.append('pub fn numerical_output_length(method:&str,input:usize)->Option<usize> {match method {')
for name,shape in s['numerical_output_shapes'].items():r.append(f'"{name}"=>Some('+('1' if shape=='scalar' else 'input')+'),')
r.append('_=>None,}}')
c.append('static inline uint64_t cosmo_numerics_output_length(uint32_t operation,uint64_t input) {switch(operation) {')
for name,shape in s['numerical_output_shapes'].items():c.append(f'case COSMO_NUMERICAL_OPERATION_{macro(name)}:return '+('1' if shape=='scalar' else 'input')+';')
c.append('default:return UINT64_MAX;}}')
c+=['#ifdef __cplusplus','}','#endif']
(root/'cpp/include/irred/abi.h').write_text('\n'.join(c)+'\n');(root/'src/abi_generated.rs').write_text('\n'.join(r)+'\n')
checks=[]
for group,enum in [('unit','Unit'),('role','Role'),('frame','Frame'),('convention','LengthConvention'),('quantity_status','QuantityStatus')]:
 for name in s['quantity_tags'][group]:checks.append(f'static_assert(static_cast<uint32_t>(irred::{enum}::{name}) == COSMO_{macro(group)}_{macro(name)});')
for name in s['numerical_tags']['status']:checks.append(f'static_assert(static_cast<uint32_t>(irred::numerics::Status::{name}) == COSMO_NUMERICAL_STATUS_{macro(name)});')
(root/'cpp/include/irred/quantity_enum_checks.inc').write_text('// Generated structural ID agreement; physical semantics owned by quantities.cpp.\n'+'\n'.join(checks)+'\n')
observation_checks=[]
for group,enum in [('profile','Profile'),('role','Role'),('unit','Unit'),('calibration','Calibration'),('uncertainty','Uncertainty'),('uncertainty_unit','UncertaintyUnit'),('component','Component'),('selection','Selection'),('status','Status')]:
 for name in s.get('observation_tags',{}).get(group,{}):
  observation_checks.append(f'static_assert(static_cast<uint32_t>(irred::observations::{enum}::{name}) == COSMO_OBSERVATION_{macro(group)}_{macro(name)});')
(root/'cpp/include/irred/observation_enum_checks.inc').write_text('// Generated structural observation tag agreement.\n'+'\n'.join(observation_checks)+'\n')
subprocess.run(['rustfmt',str(root/'src/abi_generated.rs')],check=True)

# Agent-facing JSON metadata enum views use the same structural tag source.
run_path=root/'schema/run.schema.json'
existing=json.loads(run_path.read_text())
fixture=existing.get('$defs',{}).get('fixture',existing)
metadata={'type':'object','additionalProperties':False,'required':[g for g in s['quantity_tags'] if g!='quantity_status'],'properties':{g:{'type':'string','enum':list(tags)} for g,tags in s['quantity_tags'].items() if g!='quantity_status'}}
quantity={'type':'object','additionalProperties':False,'required':['schema_version','operation','values','source','target'],'properties':{'schema_version':{'const':1},'operation':{'const':'quantity.convert.v1'},'values':{'type':'array','items':{'type':'number'}},'source':{'$ref':'#/$defs/quantity_metadata'},'target':{'$ref':'#/$defs/quantity_metadata'}}}
numerics={'type':'object','additionalProperties':False,'required':['schema_version','operation','method','values'],'properties':{'schema_version':{'const':1},'operation':{'const':'numerics.scalar_batch.v1'},'method':{'enum':list(s['numerical_tags']['operation'])},'values':{'type':'array','maxItems':s['max_batch_elements'],'items':{'type':'number'}}}}
observation_metadata={'type':'object','additionalProperties':False,'required':[g for g in s['observation_tags'] if g not in ['selection','status']],'properties':{g:{'type':'string','enum':list(tags)} for g,tags in s['observation_tags'].items() if g not in ['selection','status']}}
observations={'type':'object','additionalProperties':False,'required':['schema_version','operation','table','metadata','selection','resources'],'properties':{'schema_version':{'const':1},'operation':{'const':'observations.prepare.v1'},'table':{'type':'string'},'uncertainty':{'type':['string','null']},'metadata':{'$ref':'#/$defs/observation_metadata'},'selection':{'enum':list(s['observation_tags']['selection'])},'resources':{'type':'object','additionalProperties':False,'required':['maximum_asset_bytes','maximum_rows','maximum_matrix_elements','maximum_string_bytes'],'properties':{k:{'type':'integer','minimum':0,'maximum':v} for k,v in {'maximum_asset_bytes':268435456,'maximum_rows':10000,'maximum_matrix_elements':25000000,'maximum_string_bytes':16777216}.items()}},'source_selection':{'type':'array','maxItems':10000,'items':{'type':'integer','enum':[0,1]}}}}
for field in ['calibration_provenance','dependence_provenance','quality_dictionary','ordering_provenance']:observations['properties'][field]={'type':'string'}
run={'$schema':'https://json-schema.org/draft/2020-12/schema','$id':'cosmology.run.v1','oneOf':[{'$ref':'#/$defs/fixture'},{'$ref':'#/$defs/quantity'},{'$ref':'#/$defs/numerics'},{'$ref':'#/$defs/observations'}],'$defs':{'fixture':fixture,'quantity':quantity,'quantity_metadata':metadata,'numerics':numerics,'observations':observations,'observation_metadata':observation_metadata},'description':'Structural generated view. C++ owns scientific admissibility, conversions and per-row statuses; successful execution without qualification remains unaccepted.'}
# Retained Gaussian requests reuse the exact observation acquisition contract.
prior={'type':['object','null'],'additionalProperties':False,'required':['response','ordered_ids','mean','variance','latent_identity','independence_declared'],'properties':{'response':{'type':'array','items':{'type':'number'}},'ordered_ids':{'type':'array','items':{'type':'string'}},'mean':{'type':'number'},'variance':{'type':'number','exclusiveMinimum':0},'latent_identity':{'type':'string','minLength':1},'independence_declared':{'type':'boolean'}}}
gaussian={'type':'object','additionalProperties':False,'required':['schema_version','operation','observations','mode','residual_unit','response_unit','ordered_ids','residuals','maximum_batch_elements','maximum_forward_sensitivity'],'properties':{'schema_version':{'const':1},'operation':{'const':'statistics.gaussian_batch.v1'},'observations':{'$ref':'#/$defs/observations'},'mode':{'enum':list(s['gaussian_tags']['mode'])},'residual_unit':{'enum':list(s['observation_tags']['unit'])},'response_unit':{'const':'one'},'ordered_ids':{'type':'array','maxItems':10000,'items':{'type':'string'}},'residuals':{'type':'array','maxItems':s['max_batch_elements'],'items':{'type':'array','maxItems':10000,'items':{'type':'number'}}},'response':{'type':['array','null'],'items':{'type':'number'}},'proper_prior':prior,'maximum_batch_elements':{'type':'integer','minimum':0,'maximum':s['max_batch_elements']},'maximum_forward_sensitivity':{'type':'number','exclusiveMinimum':0}}}
run['$defs']['gaussian']=gaussian;run['oneOf'].append({'$ref':'#/$defs/gaussian'})
background_parameters={'type':'object','additionalProperties':False,'required':['model','h0_km_s_mpc','omega_m','constant_q'],'properties':{'model':{'enum':list(s['background_tags']['model'])},'h0_km_s_mpc':{'type':'number'},'omega_m':{'type':'number'},'constant_q':{'type':'number'}}}
background_query={'type':'object','additionalProperties':False,'required':['z_expansion','z_observer','convention'],'properties':{'z_expansion':{'type':'number'},'z_observer':{'type':'number'},'convention':{'enum':list(s['background_tags']['convention'])}}}
background_policy={'type':'object','additionalProperties':False,'required':['maximum_parameters','maximum_queries','maximum_slots','maximum_native_output_bytes','maximum_total_evaluations','maximum_evaluations_per_integral','maximum_depth','absolute_tolerance','relative_tolerance'],'properties':{k:{'type':'integer','minimum':0,'maximum':v} for k,v in {'maximum_parameters':4096,'maximum_queries':4096,'maximum_slots':s['max_batch_elements'],'maximum_native_output_bytes':536870912,'maximum_total_evaluations':18446744073709551615,'maximum_evaluations_per_integral':18446744073709551615,'maximum_depth':64}.items()}}
background_policy['properties']['maximum_depth']['minimum']=1;background_policy['properties']['maximum_evaluations_per_integral']['minimum']=3
for field in ['absolute_tolerance','relative_tolerance']:background_policy['properties'][field]={'type':'number','minimum':0}
background_policy['anyOf']=[{'properties':{'absolute_tolerance':{'exclusiveMinimum':0}}},{'properties':{'relative_tolerance':{'exclusiveMinimum':0}}}]
background={'type':'object','additionalProperties':False,'required':['schema_version','operation','parameters','queries','policy'],'properties':{'schema_version':{'const':1},'operation':{'const':'background.parameter_query_batch.v1'},'parameters':{'type':'array','maxItems':4096,'items':background_parameters},'queries':{'type':'array','maxItems':4096,'items':background_query},'policy':background_policy},'description':'Parameter-major Cartesian batch; CLI total JSON slots<=65536, native output storage and global integration callbacks bounded before allocation. Structural view only; C++ owns model domains/conventions.'}
run['$defs']['background']=background;run['oneOf'].append({'$ref':'#/$defs/background'})
supernova_model={'type':'object','additionalProperties':False,'required':['model','omega_m','constant_q'],'properties':{'model':{'enum':list(s['background_tags']['model'])},'omega_m':{'type':'number'},'constant_q':{'type':'number'}}}
supernova_policy={'type':'object','additionalProperties':False,'required':['arithmetic','include_residual_arrays','maximum_models','maximum_source_rows','maximum_matrix_elements','maximum_array_elements','maximum_native_output_bytes','maximum_total_evaluations','maximum_evaluations_per_integral','maximum_depth','absolute_tolerance','relative_tolerance','maximum_forward_sensitivity'],'properties':{k:{'type':'integer','minimum':0,'maximum':v} for k,v in {'maximum_models':64,'maximum_source_rows':4096,'maximum_matrix_elements':16777216,'maximum_array_elements':s['max_batch_elements'],'maximum_native_output_bytes':536870912,'maximum_total_evaluations':18446744073709551615,'maximum_evaluations_per_integral':18446744073709551615,'maximum_depth':64}.items()}}
supernova_policy['properties'].update({'arithmetic':{'enum':list(s['supernova_tags']['arithmetic'])},'include_residual_arrays':{'type':'boolean'},'maximum_forward_sensitivity':{'type':'number','exclusiveMinimum':0},'absolute_tolerance':{'type':'number','minimum':0},'relative_tolerance':{'type':'number','minimum':0}})
supernova_policy['properties']['maximum_depth']['minimum']=1;supernova_policy['properties']['maximum_evaluations_per_integral']['minimum']=3
supernova_policy['anyOf']=[{'properties':{'absolute_tolerance':{'exclusiveMinimum':0}}},{'properties':{'relative_tolerance':{'exclusiveMinimum':0}}}]
run['$defs']['supernova']={'type':'object','additionalProperties':False,'required':['schema_version','operation','observations','models','policy'],'properties':{'schema_version':{'const':1},'operation':{'const':'supernova.profile_batch.v1'},'observations':{'$ref':'#/$defs/observations'},'models':{'type':'array','maxItems':64,'items':supernova_model},'policy':supernova_policy},'description':'Retained compiled released-source relative single-offset profile batch; requires Pantheon profile and strict zHD>.01 selection. No density/evidence claim.'}
run['oneOf'].append({'$ref':'#/$defs/supernova'})
run_path.write_text(json.dumps(run,indent=2)+'\n')
