#!/usr/bin/env python3
"""Check generated byte/mtime stability and real schema-change invalidation."""
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest
from build_files import write_if_changed


class BuildFilesTests(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.root = Path(self.directory.name)

    def test_missing_changed_and_identical_bytes(self):
        path = self.root / "input"
        write_if_changed(path, "first\n")
        self.assertEqual(path.read_bytes(), b"first\n")
        os.utime(path, ns=(1_000_000_000, 1_000_000_000))
        write_if_changed(path, "first\n")
        self.assertEqual(path.stat().st_mtime_ns, 1_000_000_000)
        write_if_changed(path, "second\n")
        self.assertEqual(path.read_bytes(), b"second\n")
        self.assertNotEqual(path.stat().st_mtime_ns, 1_000_000_000)

    def test_comparison_is_bytes_not_decoded_newlines(self):
        path = self.root / "input"
        path.write_bytes(b"first\r\n")
        write_if_changed(path, "first\n")
        self.assertEqual(path.read_bytes(), b"first\n")

    def test_write_errors_are_not_suppressed(self):
        with self.assertRaises(FileNotFoundError):
            write_if_changed(self.root / "missing" / "input", "first\n")

    def test_generator_preserves_final_outputs_and_updates_changed_schema(self):
        source = Path(__file__).resolve().parents[1]
        for directory in ("tools", "schema", "src", "cpp/include/irred"):
            (self.root / directory).mkdir(parents=True)
        for name in ("generate_abi.py", "run_schema.py", "build_files.py"):
            shutil.copyfile(source / "tools" / name, self.root / "tools" / name)
        for name in ("abi.json", "run.schema.json"):
            shutil.copyfile(source / "schema" / name, self.root / "schema" / name)
        outputs = [self.root / name for name in (
            "cpp/include/irred/abi.h", "cpp/include/irred/quantity_enum_checks.inc",
            "cpp/include/irred/observation_enum_checks.inc", "src/abi_generated.rs",
            "schema/run.schema.json")]

        def generate():
            subprocess.run(["python3", str(self.root / "tools/generate_abi.py")], check=True)

        generate()
        for path in outputs:
            self.assertEqual(path.read_bytes(), (source / path.relative_to(self.root)).read_bytes())
            os.utime(path, ns=(1_000_000_000, 1_000_000_000))
        generate()
        self.assertTrue(all(path.stat().st_mtime_ns == 1_000_000_000 for path in outputs))
        schema_path = self.root / "schema/abi.json"
        schema = json.loads(schema_path.read_text())
        schema["max_batch_elements"] += 1
        schema_path.write_text(json.dumps(schema))
        generate()
        self.assertIn(f'#define IRRED_MAX_BATCH_ELEMENTS {schema["max_batch_elements"]}u', outputs[0].read_text())
        self.assertIn(f'pub const MAX_BATCH_ELEMENTS: u64 = {schema["max_batch_elements"]};', outputs[3].read_text())
        self.assertNotEqual(outputs[0].stat().st_mtime_ns, 1_000_000_000)
        self.assertNotEqual(outputs[3].stat().st_mtime_ns, 1_000_000_000)


if __name__ == "__main__":
    unittest.main()
