// Generated by tools/generate_abi.py; edit schema/abi.json.
pub const ABI_VERSION: u32 = 1;
pub const OK: u32 = 0;
pub const ABI_MISMATCH: u32 = 1;
pub const INVALID_INPUT: u32 = 2;
pub const OVERFLOW: u32 = 3;
pub const ALLOCATION_FAILURE: u32 = 4;
pub const EXCEPTION: u32 = 5;
pub const MAX_BATCH_ELEMENTS: u64 = 1000000;
pub const OBSERVATION_PROFILE_PANTHEON_PLUS_RELEASED_V1: u32 = 0;
pub const OBSERVATION_PROFILE_GAUSSIAN_FIXTURE_V1: u32 = 1;
pub const OBSERVATION_PROFILE_FITS_LENGTH_FIXTURE_V1: u32 = 2;
pub const OBSERVATION_ROLE_OBSERVED_MEASUREMENT: u32 = 0;
pub const OBSERVATION_ROLE_RELEASED_FITTED_SUMMARY: u32 = 1;
pub const OBSERVATION_ROLE_SYNTHETIC_CONTROL: u32 = 2;
pub const OBSERVATION_ROLE_POSTERIOR_SUMMARY: u32 = 3;
pub const OBSERVATION_UNIT_MAGNITUDE: u32 = 0;
pub const OBSERVATION_UNIT_METRE: u32 = 1;
pub const OBSERVATION_CALIBRATION_UNKNOWN: u32 = 0;
pub const OBSERVATION_CALIBRATION_RELEASED_CORRECTED: u32 = 1;
pub const OBSERVATION_CALIBRATION_NOT_APPLICABLE: u32 = 2;
pub const OBSERVATION_UNCERTAINTY_NONE: u32 = 0;
pub const OBSERVATION_UNCERTAINTY_COVARIANCE: u32 = 1;
pub const OBSERVATION_UNCERTAINTY_PRECISION: u32 = 2;
pub const OBSERVATION_UNCERTAINTY_UNIT_NONE: u32 = 0;
pub const OBSERVATION_UNCERTAINTY_UNIT_MAGNITUDE_SQUARED: u32 = 1;
pub const OBSERVATION_UNCERTAINTY_UNIT_INVERSE_MAGNITUDE_SQUARED: u32 = 2;
pub const OBSERVATION_UNCERTAINTY_UNIT_METRE_SQUARED: u32 = 3;
pub const OBSERVATION_UNCERTAINTY_UNIT_INVERSE_METRE_SQUARED: u32 = 4;
pub const OBSERVATION_COMPONENT_UNKNOWN: u32 = 0;
pub const OBSERVATION_COMPONENT_STATISTICAL: u32 = 1;
pub const OBSERVATION_COMPONENT_SYSTEMATIC: u32 = 2;
pub const OBSERVATION_COMPONENT_TOTAL: u32 = 3;
pub const OBSERVATION_SELECTION_ALL: u32 = 0;
pub const OBSERVATION_SELECTION_PANTHEON_ZHD_GT_001: u32 = 1;
pub const OBSERVATION_STATUS_OK: u32 = 0;
pub const OBSERVATION_STATUS_INVALID_SHAPE: u32 = 1;
pub const OBSERVATION_STATUS_INVALID_IDENTITY: u32 = 2;
pub const OBSERVATION_STATUS_INCOMPATIBLE_SEMANTICS: u32 = 3;
pub const OBSERVATION_STATUS_MISSING_REQUIRED_VALUE: u32 = 4;
pub const OBSERVATION_STATUS_NONFINITE_REQUIRED_VALUE: u32 = 5;
pub const OBSERVATION_STATUS_RESOURCE_LIMIT: u32 = 6;
pub const GAUSSIAN_MODE_NORMALIZED_DENSITY: u32 = 0;
pub const GAUSSIAN_MODE_PROFILE_OFFSET_SCORE: u32 = 1;
pub const GAUSSIAN_STATUS_FINITE: u32 = 0;
pub const GAUSSIAN_STATUS_OUTSIDE_SUPPORT: u32 = 1;
pub const GAUSSIAN_STATUS_INVALID_INPUT: u32 = 2;
pub const GAUSSIAN_STATUS_UNSUPPORTED_DOMAIN: u32 = 3;
pub const GAUSSIAN_STATUS_NUMERICAL_FAILURE: u32 = 4;
pub const GAUSSIAN_STATUS_INCOMPATIBLE_METADATA: u32 = 5;
pub const GAUSSIAN_MATRIX_VALIDATION_SCOPE_FULL_DECLARED_MATRIX: u32 = 0;
pub const GAUSSIAN_MATRIX_VALIDATION_SCOPE_SELECTED_COVARIANCE_ONLY: u32 = 1;
pub const GAUSSIAN_MATRIX_VALIDATION_SCOPE_FULL_PRECISION_THEN_MARGINAL: u32 = 2;
pub fn gaussian_status_name(value: u32) -> Option<&'static str> {
    match value {
        0 => Some("finite"),
        1 => Some("outside_support"),
        2 => Some("invalid_input"),
        3 => Some("unsupported_domain"),
        4 => Some("numerical_failure"),
        5 => Some("incompatible_metadata"),
        _ => None,
    }
}
#[repr(C)]
pub struct Buffer {
    pub struct_size: u32,
    pub abi_version: u32,
    pub element_type: u32,
    pub reserved: u32,
    pub data: *const i64,
    pub length: u64,
    pub byte_length: u64,
}
#[repr(C)]
pub struct F64Buffer {
    pub struct_size: u32,
    pub abi_version: u32,
    pub element_type: u32,
    pub reserved: u32,
    pub data: *const f64,
    pub length: u64,
    pub byte_length: u64,
}
#[repr(C)]
pub struct QuantityMetadata {
    pub struct_size: u32,
    pub abi_version: u32,
    pub unit: u32,
    pub role: u32,
    pub frame: u32,
    pub convention: u32,
    pub constant_set: u32,
    pub reserved: u32,
}
#[repr(C)]
pub struct Bytes {
    pub data: *const u8,
    pub length: u64,
}
#[repr(C)]
pub struct Strings {
    pub data: *const Bytes,
    pub length: u64,
    pub byte_length: u64,
}
#[repr(C)]
pub struct U8Buffer {
    pub data: *const u8,
    pub length: u64,
    pub byte_length: u64,
}
#[repr(C)]
pub struct U64Buffer {
    pub data: *const u64,
    pub length: u64,
    pub byte_length: u64,
}
#[repr(C)]
pub struct ObservationPolicy {
    pub maximum_rows: u64,
    pub maximum_matrix_elements: u64,
    pub maximum_string_bytes: u64,
}
#[repr(C)]
pub struct ObservationDescriptor {
    pub struct_size: u32,
    pub abi_version: u32,
    pub reserved: u32,
    pub profile: u32,
    pub role: u32,
    pub unit: u32,
    pub calibration: u32,
    pub uncertainty: u32,
    pub uncertainty_unit: u32,
    pub component: u32,
    pub table_sha256: Bytes,
    pub uncertainty_sha256: Bytes,
    pub calibration_provenance: Bytes,
    pub dependence_provenance: Bytes,
    pub quality_dictionary: Bytes,
    pub ordering_provenance: Bytes,
    pub measurement_ids: Strings,
    pub event_ids: Strings,
    pub uncertainty_axis_ids: Strings,
    pub values: F64Buffer,
    pub zhd: F64Buffer,
    pub zcmb: F64Buffer,
    pub zhel: F64Buffer,
    pub uncertainty_matrix: F64Buffer,
    pub missing: U8Buffer,
    pub zhd_missing: U8Buffer,
    pub zcmb_missing: U8Buffer,
    pub zhel_missing: U8Buffer,
    pub source_selection: U8Buffer,
    pub quality: U64Buffer,
}
#[repr(C)]
pub struct GaussianPolicy {
    pub struct_size: u32,
    pub abi_version: u32,
    pub reserved: u32,
    pub reserved2: u32,
    pub maximum_matrix_elements: u64,
    pub maximum_batch_elements: u64,
    pub maximum_string_bytes: u64,
    pub maximum_forward_sensitivity: f64,
}
#[repr(C)]
pub struct GaussianBatch {
    pub struct_size: u32,
    pub abi_version: u32,
    pub mode: u32,
    pub reserved: u32,
    pub row_count: u64,
    pub residuals: F64Buffer,
    pub ordered_ids: Strings,
    pub response: F64Buffer,
}
#[repr(C)]
pub struct GaussianRow {
    pub status: u32,
    pub numerical_status: u32,
    pub log_density: f64,
    pub quadratic: f64,
    pub log_determinant: f64,
    pub normalization: f64,
    pub backward_residual: f64,
    pub estimated_forward_sensitivity: f64,
    pub coefficient: f64,
}
#[repr(C)]
pub struct GaussianView {
    pub struct_size: u32,
    pub abi_version: u32,
    pub matrix_validation_scope: u32,
    pub ordered_ids: Strings,
    pub measure: Bytes,
    pub table_identity: Bytes,
    pub uncertainty_identity: Bytes,
    pub ordering_provenance: Bytes,
    pub calibration_provenance: Bytes,
    pub dependence_provenance: Bytes,
    pub source_semantics: Bytes,
    pub input_matrix_convention: Bytes,
    pub treatment: Bytes,
    pub mean_shift: F64Buffer,
    pub prior_count: u64,
    pub selection_count: u64,
}
#[repr(C)]
pub struct GaussianPrior {
    pub struct_size: u32,
    pub abi_version: u32,
    pub independence_declared: u32,
    pub reserved: u32,
    pub mean: f64,
    pub variance: f64,
    pub latent_identity: Bytes,
    pub response: F64Buffer,
    pub ordered_ids: Strings,
}
#[repr(C)]
pub struct GaussianSelection {
    pub struct_size: u32,
    pub abi_version: u32,
    pub operation: Bytes,
    pub kept_row_ids: Strings,
    pub complement_row_ids: Strings,
}
unsafe extern "C" {
    pub fn cosmo_add(
        a: *const Buffer,
        b: *const Buffer,
        fault: u32,
        out: *mut *mut std::ffi::c_void,
    ) -> u32;
    pub fn cosmo_result_view(r: *const std::ffi::c_void, data: *mut *const i64, n: *mut u64)
        -> u32;
    pub fn cosmo_result_destroy(r: *mut std::ffi::c_void) -> u32;
    pub fn cosmo_convert_quantities(
        values: *const F64Buffer,
        source: *const QuantityMetadata,
        target: *const QuantityMetadata,
        out: *mut *mut std::ffi::c_void,
    ) -> u32;
    pub fn cosmo_result_f64_view(
        r: *const std::ffi::c_void,
        data: *mut *const f64,
        status: *mut *const u32,
        n: *mut u64,
    ) -> u32;
    pub fn cosmo_numerics_evaluate(
        operation: u32,
        values: *const F64Buffer,
        out: *mut *mut std::ffi::c_void,
    ) -> u32;
    pub fn cosmo_result_numerics_view(
        r: *const std::ffi::c_void,
        data: *mut *const f64,
        status: *mut *const u32,
        error_estimate: *mut *const f64,
        evaluations: *mut *const u64,
        n: *mut u64,
    ) -> u32;
    pub fn cosmo_prepare_observations(
        descriptor: *const ObservationDescriptor,
        policy: *const ObservationPolicy,
        out: *mut *mut std::ffi::c_void,
        semantic_status: *mut u32,
    ) -> u32;
    pub fn cosmo_observation_source_view(
        prepared: *const std::ffi::c_void,
        descriptor: *mut ObservationDescriptor,
    ) -> u32;
    pub fn cosmo_observation_select(
        prepared: *const std::ffi::c_void,
        selection: u32,
        out: *mut *mut std::ffi::c_void,
        semantic_status: *mut u32,
    ) -> u32;
    pub fn cosmo_result_selection_view(
        result: *const std::ffi::c_void,
        mask: *mut *const u8,
        mask_length: *mut u64,
        indices: *mut *const u64,
        index_length: *mut u64,
    ) -> u32;
    pub fn cosmo_observation_destroy(prepared: *mut std::ffi::c_void) -> u32;
    pub fn cosmo_gaussian_prepare(
        observations: *const std::ffi::c_void,
        selection: u32,
        policy: *const GaussianPolicy,
        out: *mut *mut std::ffi::c_void,
        semantic: *mut u32,
    ) -> u32;
    pub fn cosmo_gaussian_proper_offset(
        gaussian: *const std::ffi::c_void,
        prior: *const GaussianPrior,
        policy: *const GaussianPolicy,
        out: *mut *mut std::ffi::c_void,
        semantic: *mut u32,
    ) -> u32;
    pub fn cosmo_gaussian_source_view(
        gaussian: *const std::ffi::c_void,
        out: *mut GaussianView,
    ) -> u32;
    pub fn cosmo_gaussian_prior_view(
        gaussian: *const std::ffi::c_void,
        index: u64,
        out: *mut GaussianPrior,
    ) -> u32;
    pub fn cosmo_gaussian_evaluate(
        gaussian: *const std::ffi::c_void,
        batch: *const GaussianBatch,
        policy: *const GaussianPolicy,
        out: *mut *mut std::ffi::c_void,
    ) -> u32;
    pub fn cosmo_gaussian_result_view(
        result: *const std::ffi::c_void,
        rows: *mut *const GaussianRow,
        length: *mut u64,
    ) -> u32;
    pub fn cosmo_gaussian_destroy(gaussian: *mut std::ffi::c_void) -> u32;
    pub fn cosmo_gaussian_result_destroy(result: *mut std::ffi::c_void) -> u32;
    pub fn cosmo_gaussian_selection_view(
        gaussian: *const std::ffi::c_void,
        index: u64,
        out: *mut GaussianSelection,
    ) -> u32;
}
#[derive(Clone, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct MetadataFields {
    pub unit: String,
    pub role: String,
    pub frame: String,
    pub convention: String,
    pub constant_set: String,
}
pub fn tag_id(group: &str, label: &str) -> Option<u32> {
    match (group, label) {
        ("unit", "one") => Some(1),
        ("unit", "metre") => Some(2),
        ("unit", "kilometre") => Some(3),
        ("unit", "second") => Some(4),
        ("unit", "day") => Some(5),
        ("unit", "inverse_second") => Some(6),
        ("unit", "parsec") => Some(7),
        ("unit", "megaparsec") => Some(8),
        ("unit", "km_per_s_per_mpc") => Some(9),
        ("role", "ratio") => Some(1),
        ("role", "redshift") => Some(2),
        ("role", "physical_length") => Some(3),
        ("role", "comoving_distance") => Some(4),
        ("role", "luminosity_distance") => Some(5),
        ("role", "angular_diameter_distance") => Some(6),
        ("role", "duration") => Some(7),
        ("role", "expansion_rate") => Some(8),
        ("frame", "none") => Some(0),
        ("frame", "heliocentric") => Some(1),
        ("frame", "cmb") => Some(2),
        ("frame", "model") => Some(3),
        ("convention", "none") => Some(0),
        ("convention", "physical") => Some(1),
        ("convention", "comoving_a0_one") => Some(2),
        ("constant_set", "SI-IAU-definitions-v1") => Some(1),
        ("quantity_status", "ok") => Some(0),
        ("quantity_status", "unknown_unit") => Some(1),
        ("quantity_status", "dimension_mismatch") => Some(2),
        ("quantity_status", "role_mismatch") => Some(3),
        ("quantity_status", "missing_convention") => Some(4),
        ("quantity_status", "unsupported_transform") => Some(5),
        ("quantity_status", "nonfinite_input") => Some(6),
        ("quantity_status", "overflow") => Some(7),
        ("quantity_status", "underflow") => Some(8),
        ("quantity_status", "constant_set_mismatch") => Some(9),
        ("quantity_status", "invalid_domain") => Some(10),
        ("quantity_status", "invalid_batch") => Some(11),
        _ => None,
    }
}
pub fn quantity_status_name(value: u32) -> Option<&'static str> {
    match value {
        0 => Some("ok"),
        1 => Some("unknown_unit"),
        2 => Some("dimension_mismatch"),
        3 => Some("role_mismatch"),
        4 => Some("missing_convention"),
        5 => Some("unsupported_transform"),
        6 => Some("nonfinite_input"),
        7 => Some("overflow"),
        8 => Some("underflow"),
        9 => Some("constant_set_mismatch"),
        10 => Some("invalid_domain"),
        11 => Some("invalid_batch"),
        _ => None,
    }
}
#[derive(Clone, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct ObservationMetadataFields {
    pub profile: String,
    pub role: String,
    pub unit: String,
    pub calibration: String,
    pub uncertainty: String,
    pub uncertainty_unit: String,
    pub component: String,
}
pub fn observation_tag_id(group: &str, label: &str) -> Option<u32> {
    match (group, label) {
        ("profile", "pantheon_plus_released_v1") => Some(0),
        ("profile", "gaussian_fixture_v1") => Some(1),
        ("profile", "fits_length_fixture_v1") => Some(2),
        ("role", "observed_measurement") => Some(0),
        ("role", "released_fitted_summary") => Some(1),
        ("role", "synthetic_control") => Some(2),
        ("role", "posterior_summary") => Some(3),
        ("unit", "magnitude") => Some(0),
        ("unit", "metre") => Some(1),
        ("calibration", "unknown") => Some(0),
        ("calibration", "released_corrected") => Some(1),
        ("calibration", "not_applicable") => Some(2),
        ("uncertainty", "none") => Some(0),
        ("uncertainty", "covariance") => Some(1),
        ("uncertainty", "precision") => Some(2),
        ("uncertainty_unit", "none") => Some(0),
        ("uncertainty_unit", "magnitude_squared") => Some(1),
        ("uncertainty_unit", "inverse_magnitude_squared") => Some(2),
        ("uncertainty_unit", "metre_squared") => Some(3),
        ("uncertainty_unit", "inverse_metre_squared") => Some(4),
        ("component", "unknown") => Some(0),
        ("component", "statistical") => Some(1),
        ("component", "systematic") => Some(2),
        ("component", "total") => Some(3),
        ("selection", "all") => Some(0),
        ("selection", "pantheon_zhd_gt_001") => Some(1),
        ("status", "ok") => Some(0),
        ("status", "invalid_shape") => Some(1),
        ("status", "invalid_identity") => Some(2),
        ("status", "incompatible_semantics") => Some(3),
        ("status", "missing_required_value") => Some(4),
        ("status", "nonfinite_required_value") => Some(5),
        ("status", "resource_limit") => Some(6),
        _ => None,
    }
}
pub fn observation_status_name(value: u32) -> Option<&'static str> {
    match value {
        0 => Some("ok"),
        1 => Some("invalid_shape"),
        2 => Some("invalid_identity"),
        3 => Some("incompatible_semantics"),
        4 => Some("missing_required_value"),
        5 => Some("nonfinite_required_value"),
        6 => Some("resource_limit"),
        _ => None,
    }
}
pub fn numerical_operation_id(label: &str) -> Option<u32> {
    match label {
        "compensated_sum" => Some(1),
        "log_sum_exp" => Some(2),
        "log1p" => Some(3),
        "expm1" => Some(4),
        "log_gamma_positive" => Some(5),
        _ => None,
    }
}
pub fn numerical_status_name(value: u32) -> Option<&'static str> {
    match value {
        0 => Some("ok"),
        1 => Some("invalid_input"),
        2 => Some("nonfinite_input"),
        3 => Some("overflow"),
        4 => Some("work_limit"),
        5 => Some("outside_domain"),
        6 => Some("singular"),
        7 => Some("not_positive_definite"),
        8 => Some("conditioning_budget_exceeded"),
        _ => None,
    }
}
pub fn numerical_output_length(method: &str, input: usize) -> Option<usize> {
    match method {
        "compensated_sum" => Some(1),
        "log_sum_exp" => Some(1),
        "log1p" => Some(input),
        "expm1" => Some(input),
        "log_gamma_positive" => Some(input),
        _ => None,
    }
}
