// Generated by tools/generate_abi.py; edit schema/abi.json.
pub const ABI_VERSION: u32 = 2;
pub const OK: u32 = 0;
pub const ABI_MISMATCH: u32 = 1;
pub const INVALID_INPUT: u32 = 2;
pub const OVERFLOW: u32 = 3;
pub const ALLOCATION_FAILURE: u32 = 4;
pub const EXCEPTION: u32 = 5;
pub const MAX_BATCH_ELEMENTS: u64 = 1000000;
pub const OBSERVATION_PROFILE_PANTHEON_PLUS_RELEASED_V1: u32 = 0;
pub const OBSERVATION_PROFILE_GAUSSIAN_FIXTURE_V1: u32 = 1;
pub const OBSERVATION_PROFILE_FITS_LENGTH_FIXTURE_V1: u32 = 2;
pub const OBSERVATION_PROFILE_TYPED_MAGNITUDE_COVARIANCE: u32 = 3;
pub const OBSERVATION_ROLE_OBSERVED_MEASUREMENT: u32 = 0;
pub const OBSERVATION_ROLE_RELEASED_FITTED_SUMMARY: u32 = 1;
pub const OBSERVATION_ROLE_SYNTHETIC_CONTROL: u32 = 2;
pub const OBSERVATION_ROLE_POSTERIOR_SUMMARY: u32 = 3;
pub const OBSERVATION_UNIT_MAGNITUDE: u32 = 0;
pub const OBSERVATION_UNIT_METRE: u32 = 1;
pub const OBSERVATION_CALIBRATION_UNKNOWN: u32 = 0;
pub const OBSERVATION_CALIBRATION_RELEASED_CORRECTED: u32 = 1;
pub const OBSERVATION_CALIBRATION_NOT_APPLICABLE: u32 = 2;
pub const OBSERVATION_UNCERTAINTY_NONE: u32 = 0;
pub const OBSERVATION_UNCERTAINTY_COVARIANCE: u32 = 1;
pub const OBSERVATION_UNCERTAINTY_PRECISION: u32 = 2;
pub const OBSERVATION_UNCERTAINTY_UNIT_NONE: u32 = 0;
pub const OBSERVATION_UNCERTAINTY_UNIT_MAGNITUDE_SQUARED: u32 = 1;
pub const OBSERVATION_UNCERTAINTY_UNIT_INVERSE_MAGNITUDE_SQUARED: u32 = 2;
pub const OBSERVATION_UNCERTAINTY_UNIT_METRE_SQUARED: u32 = 3;
pub const OBSERVATION_UNCERTAINTY_UNIT_INVERSE_METRE_SQUARED: u32 = 4;
pub const OBSERVATION_COMPONENT_UNKNOWN: u32 = 0;
pub const OBSERVATION_COMPONENT_STATISTICAL: u32 = 1;
pub const OBSERVATION_COMPONENT_SYSTEMATIC: u32 = 2;
pub const OBSERVATION_COMPONENT_TOTAL: u32 = 3;
pub const OBSERVATION_SELECTION_ALL: u32 = 0;
pub const OBSERVATION_SELECTION_PANTHEON_ZHD_GT_001: u32 = 1;
pub const OBSERVATION_STATUS_OK: u32 = 0;
pub const OBSERVATION_STATUS_INVALID_SHAPE: u32 = 1;
pub const OBSERVATION_STATUS_INVALID_IDENTITY: u32 = 2;
pub const OBSERVATION_STATUS_INCOMPATIBLE_SEMANTICS: u32 = 3;
pub const OBSERVATION_STATUS_MISSING_REQUIRED_VALUE: u32 = 4;
pub const OBSERVATION_STATUS_NONFINITE_REQUIRED_VALUE: u32 = 5;
pub const OBSERVATION_STATUS_RESOURCE_LIMIT: u32 = 6;
pub const GAUSSIAN_MODE_NORMALIZED_DENSITY: u32 = 0;
pub const GAUSSIAN_MODE_PROFILE_OFFSET_SCORE: u32 = 1;
pub const GAUSSIAN_STATUS_FINITE: u32 = 0;
pub const GAUSSIAN_STATUS_OUTSIDE_SUPPORT: u32 = 1;
pub const GAUSSIAN_STATUS_INVALID_INPUT: u32 = 2;
pub const GAUSSIAN_STATUS_UNSUPPORTED_DOMAIN: u32 = 3;
pub const GAUSSIAN_STATUS_NUMERICAL_FAILURE: u32 = 4;
pub const GAUSSIAN_STATUS_INCOMPATIBLE_METADATA: u32 = 5;
pub const GAUSSIAN_MATRIX_VALIDATION_SCOPE_FULL_DECLARED_MATRIX: u32 = 0;
pub const GAUSSIAN_MATRIX_VALIDATION_SCOPE_SELECTED_COVARIANCE_ONLY: u32 = 1;
pub const GAUSSIAN_MATRIX_VALIDATION_SCOPE_FULL_PRECISION_THEN_MARGINAL: u32 = 2;
pub fn gaussian_status_name(value: u32) -> Option<&'static str> {
    match value {
        0 => Some("finite"),
        1 => Some("outside_support"),
        2 => Some("invalid_input"),
        3 => Some("unsupported_domain"),
        4 => Some("numerical_failure"),
        5 => Some("incompatible_metadata"),
        _ => None,
    }
}
pub const SUPERNOVA_ARITHMETIC_BINARY64_LEGACY_V1: u32 = 0;
pub const SUPERNOVA_ARITHMETIC_LONGDOUBLE_CPU_V1: u32 = 1;
pub const SUPERNOVA_STATUS_OK: u32 = 0;
pub const SUPERNOVA_STATUS_INVALID_INPUT: u32 = 1;
pub const SUPERNOVA_STATUS_INCOMPATIBLE_METADATA: u32 = 2;
pub const SUPERNOVA_STATUS_NUMERICAL_FAILURE: u32 = 3;
pub const SUPERNOVA_STATUS_WORK_LIMIT: u32 = 4;
pub fn supernova_tag_id(group: &str, label: &str) -> Option<u32> {
    match (group, label) {
        ("arithmetic", "binary64_legacy_v1") => Some(0),
        ("arithmetic", "longdouble_cpu_v1") => Some(1),
        ("status", "ok") => Some(0),
        ("status", "invalid_input") => Some(1),
        ("status", "incompatible_metadata") => Some(2),
        ("status", "numerical_failure") => Some(3),
        ("status", "work_limit") => Some(4),
        _ => None,
    }
}
pub fn supernova_status_name(value: u32) -> Option<&'static str> {
    match value {
        0 => Some("ok"),
        1 => Some("invalid_input"),
        2 => Some("incompatible_metadata"),
        3 => Some("numerical_failure"),
        4 => Some("work_limit"),
        _ => None,
    }
}
pub const BAO_OBSERVABLE_DM_OVER_RS: u32 = 0;
pub const BAO_OBSERVABLE_DH_OVER_RS: u32 = 1;
pub const BAO_OBSERVABLE_DV_OVER_RS: u32 = 2;
pub const BAO_ROLE_RELEASED_FITTED_DISTANCE_SUMMARY: u32 = 0;
pub const BAO_ROLE_SYNTHETIC_CONTROL: u32 = 1;
pub const BAO_COVARIANCE_UNIT_RATIO_SQUARED: u32 = 0;
pub fn bao_tag_id(group: &str, label: &str) -> Option<u32> {
    match (group, label) {
        ("observable", "DM_over_rs") => Some(0),
        ("observable", "DH_over_rs") => Some(1),
        ("observable", "DV_over_rs") => Some(2),
        ("role", "released_fitted_distance_summary") => Some(0),
        ("role", "synthetic_control") => Some(1),
        ("covariance_unit", "ratio_squared") => Some(0),
        _ => None,
    }
}
pub const BACKGROUND_CONVENTION_GEOMETRIC_SAME_REDSHIFT: u32 = 0;
pub const BACKGROUND_CONVENTION_RELEASED_ZHD_ZHEL: u32 = 1;
pub const BACKGROUND_STATUS_OK: u32 = 0;
pub const BACKGROUND_STATUS_INVALID_INPUT: u32 = 1;
pub const BACKGROUND_STATUS_UNSUPPORTED_DOMAIN: u32 = 2;
pub const BACKGROUND_STATUS_INCOMPATIBLE_CONVENTION: u32 = 3;
pub const BACKGROUND_STATUS_NUMERICAL_FAILURE: u32 = 4;
pub const BACKGROUND_STATUS_WORK_LIMIT: u32 = 5;
pub fn background_tag_id(group: &str, label: &str) -> Option<u32> {
    match (group, label) {
        ("convention", "geometric_same_redshift") => Some(0),
        ("convention", "released_zhd_zhel") => Some(1),
        ("status", "ok") => Some(0),
        ("status", "invalid_input") => Some(1),
        ("status", "unsupported_domain") => Some(2),
        ("status", "incompatible_convention") => Some(3),
        ("status", "numerical_failure") => Some(4),
        ("status", "work_limit") => Some(5),
        _ => None,
    }
}
pub fn background_status_name(value: u32) -> Option<&'static str> {
    match value {
        0 => Some("ok"),
        1 => Some("invalid_input"),
        2 => Some("unsupported_domain"),
        3 => Some("incompatible_convention"),
        4 => Some("numerical_failure"),
        5 => Some("work_limit"),
        _ => None,
    }
}
pub const EXPANSION_MODEL_LCDM: u32 = 0;
pub const EXPANSION_MODEL_CONSTANT_Q: u32 = 1;
pub const EXPANSION_MODEL_CPL: u32 = 2;
pub const EXPANSION_MODEL_FIXED_Q5: u32 = 3;
pub const EXPANSION_GEOMETRY_FLAT_FLRW: u32 = 0;
pub const EXPANSION_OBSERVABLE_RADIAL: u32 = 1;
pub const EXPANSION_OBSERVABLE_LUMINOSITY_SHAPE: u32 = 2;
pub const EXPANSION_OBSERVABLE_CLOCK: u32 = 4;
pub const EXPANSION_OBSERVABLE_PHYSICAL: u32 = 8;
pub const EXPANSION_OBSERVABLE_KINEMATICS: u32 = 16;
pub const EXPANSION_OBSERVABLE_EXPANSION: u32 = 32;
pub const EXPANSION_AVAILABILITY_NOT_REQUESTED: u32 = 0;
pub const EXPANSION_AVAILABILITY_AVAILABLE: u32 = 1;
pub const EXPANSION_AVAILABILITY_UNAVAILABLE: u32 = 2;
pub const EXPANSION_AVAILABILITY_FAILED: u32 = 3;
pub const EXPANSION_STATUS_OK: u32 = 0;
pub const EXPANSION_STATUS_INVALID_INPUT: u32 = 1;
pub const EXPANSION_STATUS_UNSUPPORTED_DOMAIN: u32 = 2;
pub const EXPANSION_STATUS_INCOMPATIBLE_CONVENTION: u32 = 3;
pub const EXPANSION_STATUS_NUMERICAL_FAILURE: u32 = 4;
pub const EXPANSION_STATUS_WORK_LIMIT: u32 = 5;
pub const EXPANSION_OBSERVER_CONVENTION_GEOMETRIC_SAME_REDSHIFT: u32 = 0;
pub const EXPANSION_OBSERVER_CONVENTION_RELEASED_ZHD_ZHEL: u32 = 1;
pub const EXPANSION_Q_CONVENTION_NOT_ASSESSED: u32 = 0;
pub const EXPANSION_Q_CONVENTION_INTERIOR_CONSTANT_BIN: u32 = 1;
pub const EXPANSION_Q_CONVENTION_RIGHT_LIMIT_AT_INTERNAL_JUMP: u32 = 2;
pub const EXPANSION_Q_CONVENTION_RIGHT_LIMIT_AT_ZERO: u32 = 3;
pub const EXPANSION_Q_CONVENTION_LEFT_LIMIT_AT_FINAL_ENDPOINT: u32 = 4;
pub const EXPANSION_Q_CONVENTION_ORDINARY_SMOOTH_MODEL: u32 = 5;
pub const EXPANSION_JERK_AVAILABILITY_NOT_ASSESSED: u32 = 0;
pub const EXPANSION_JERK_AVAILABILITY_ORDINARY_WITHIN_BIN: u32 = 1;
pub const EXPANSION_JERK_AVAILABILITY_ONE_SIDED_ENDPOINT: u32 = 2;
pub const EXPANSION_JERK_AVAILABILITY_UNAVAILABLE_AT_JUMP: u32 = 3;
pub fn expansion_tag_name(group: &str, value: u32) -> Option<&'static str> {
    match (group, value) {
        ("model", 0) => Some("lcdm"),
        ("model", 1) => Some("constant_q"),
        ("model", 2) => Some("cpl"),
        ("model", 3) => Some("fixed_q5"),
        ("geometry", 0) => Some("flat_flrw"),
        ("observable", 1) => Some("radial"),
        ("observable", 2) => Some("luminosity_shape"),
        ("observable", 4) => Some("clock"),
        ("observable", 8) => Some("physical"),
        ("observable", 16) => Some("kinematics"),
        ("observable", 32) => Some("expansion"),
        ("availability", 0) => Some("not_requested"),
        ("availability", 1) => Some("available"),
        ("availability", 2) => Some("unavailable"),
        ("availability", 3) => Some("failed"),
        ("status", 0) => Some("ok"),
        ("status", 1) => Some("invalid_input"),
        ("status", 2) => Some("unsupported_domain"),
        ("status", 3) => Some("incompatible_convention"),
        ("status", 4) => Some("numerical_failure"),
        ("status", 5) => Some("work_limit"),
        ("observer_convention", 0) => Some("geometric_same_redshift"),
        ("observer_convention", 1) => Some("released_zhd_zhel"),
        ("q_convention", 0) => Some("not_assessed"),
        ("q_convention", 1) => Some("interior_constant_bin"),
        ("q_convention", 2) => Some("right_limit_at_internal_jump"),
        ("q_convention", 3) => Some("right_limit_at_zero"),
        ("q_convention", 4) => Some("left_limit_at_final_endpoint"),
        ("q_convention", 5) => Some("ordinary_smooth_model"),
        ("jerk_availability", 0) => Some("not_assessed"),
        ("jerk_availability", 1) => Some("ordinary_within_bin"),
        ("jerk_availability", 2) => Some("one_sided_endpoint"),
        ("jerk_availability", 3) => Some("unavailable_at_jump"),
        _ => None,
    }
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct Buffer {
    pub struct_size: u32,
    pub abi_version: u32,
    pub element_type: u32,
    pub reserved: u32,
    pub data: *const i64,
    pub length: u64,
    pub byte_length: u64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct F64Buffer {
    pub struct_size: u32,
    pub abi_version: u32,
    pub element_type: u32,
    pub reserved: u32,
    pub data: *const f64,
    pub length: u64,
    pub byte_length: u64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct QuantityMetadata {
    pub struct_size: u32,
    pub abi_version: u32,
    pub unit: u32,
    pub role: u32,
    pub frame: u32,
    pub convention: u32,
    pub constant_set: u32,
    pub reserved: u32,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct Bytes {
    pub data: *const u8,
    pub length: u64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct Strings {
    pub data: *const Bytes,
    pub length: u64,
    pub byte_length: u64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct U8Buffer {
    pub data: *const u8,
    pub length: u64,
    pub byte_length: u64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct U64Buffer {
    pub data: *const u64,
    pub length: u64,
    pub byte_length: u64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct ObservationPolicy {
    pub maximum_rows: u64,
    pub maximum_matrix_elements: u64,
    pub maximum_string_bytes: u64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct ObservationDescriptor {
    pub struct_size: u32,
    pub abi_version: u32,
    pub reserved: u32,
    pub profile: u32,
    pub role: u32,
    pub unit: u32,
    pub calibration: u32,
    pub uncertainty: u32,
    pub uncertainty_unit: u32,
    pub component: u32,
    pub table_sha256: Bytes,
    pub uncertainty_sha256: Bytes,
    pub calibration_provenance: Bytes,
    pub dependence_provenance: Bytes,
    pub quality_dictionary: Bytes,
    pub ordering_provenance: Bytes,
    pub measurement_ids: Strings,
    pub event_ids: Strings,
    pub uncertainty_axis_ids: Strings,
    pub values: F64Buffer,
    pub zhd: F64Buffer,
    pub zcmb: F64Buffer,
    pub zhel: F64Buffer,
    pub uncertainty_matrix: F64Buffer,
    pub missing: U8Buffer,
    pub zhd_missing: U8Buffer,
    pub zcmb_missing: U8Buffer,
    pub zhel_missing: U8Buffer,
    pub source_selection: U8Buffer,
    pub quality: U64Buffer,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct GaussianPolicy {
    pub struct_size: u32,
    pub abi_version: u32,
    pub reserved: u32,
    pub reserved2: u32,
    pub maximum_matrix_elements: u64,
    pub maximum_batch_elements: u64,
    pub maximum_string_bytes: u64,
    pub maximum_forward_sensitivity: f64,
    pub maximum_native_bytes: u64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct GaussianBatch {
    pub struct_size: u32,
    pub abi_version: u32,
    pub mode: u32,
    pub reserved: u32,
    pub row_count: u64,
    pub residuals: F64Buffer,
    pub ordered_ids: Strings,
    pub response: F64Buffer,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct GaussianRow {
    pub status: u32,
    pub numerical_status: u32,
    pub log_density: f64,
    pub quadratic: f64,
    pub log_determinant: f64,
    pub normalization: f64,
    pub backward_residual: f64,
    pub estimated_forward_sensitivity: f64,
    pub coefficient: f64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct GaussianView {
    pub struct_size: u32,
    pub abi_version: u32,
    pub matrix_validation_scope: u32,
    pub ordered_ids: Strings,
    pub measure: Bytes,
    pub table_identity: Bytes,
    pub uncertainty_identity: Bytes,
    pub ordering_provenance: Bytes,
    pub calibration_provenance: Bytes,
    pub dependence_provenance: Bytes,
    pub source_semantics: Bytes,
    pub input_matrix_convention: Bytes,
    pub treatment: Bytes,
    pub mean_shift: F64Buffer,
    pub prior_count: u64,
    pub selection_count: u64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct GaussianPrior {
    pub struct_size: u32,
    pub abi_version: u32,
    pub independence_declared: u32,
    pub reserved: u32,
    pub mean: f64,
    pub variance: f64,
    pub latent_identity: Bytes,
    pub response: F64Buffer,
    pub ordered_ids: Strings,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct GaussianSelection {
    pub struct_size: u32,
    pub abi_version: u32,
    pub operation: Bytes,
    pub kept_row_ids: Strings,
    pub complement_row_ids: Strings,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct BaoQuery {
    pub z: f64,
    pub observable: u32,
    pub reserved: u32,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct ExpansionSpec {
    pub struct_size: u32,
    pub abi_version: u32,
    pub model: u32,
    pub reserved: u32,
    pub parameters: F64Buffer,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct ExpansionRequest {
    pub struct_size: u32,
    pub abi_version: u32,
    pub requested: u32,
    pub presence_flags: u32,
    pub z_expansion: f64,
    pub observer_redshift: f64,
    pub observer_convention: u32,
    pub reserved: u32,
    pub h0_km_s_mpc: f64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct ExpansionPolicy {
    pub struct_size: u32,
    pub abi_version: u32,
    pub has_integration: u32,
    pub max_depth: u32,
    pub absolute_tolerance: f64,
    pub relative_tolerance: f64,
    pub integration_max_evaluations: u64,
    pub maximum_models: u64,
    pub maximum_queries: u64,
    pub maximum_slots: u64,
    pub maximum_callbacks: u64,
    pub maximum_segment_visits: u64,
    pub maximum_native_bytes: u64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct ExpansionBatch {
    pub struct_size: u32,
    pub abi_version: u32,
    pub geometry: u32,
    pub reserved: u32,
    pub models: *const ExpansionSpec,
    pub model_count: u64,
    pub model_byte_length: u64,
    pub queries: *const ExpansionRequest,
    pub query_count: u64,
    pub query_byte_length: u64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct OutputState {
    pub availability: u32,
    pub status: u32,
    pub numerical_status: u32,
    pub reserved: u32,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct ScalarOutcome {
    pub state: OutputState,
    pub value: f64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct ExpansionOutcome {
    pub state: OutputState,
    pub E: f64,
    pub H_km_s_mpc: ScalarOutcome,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct RadialOutcome {
    pub state: OutputState,
    pub E: f64,
    pub integral: f64,
    pub error_estimate: f64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct ClockOutcome {
    pub state: OutputState,
    pub integral: f64,
    pub error_estimate: f64,
    pub lookback_seconds: ScalarOutcome,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct PhysicalOutcome {
    pub state: OutputState,
    pub radial_mpc: f64,
    pub transverse_mpc: f64,
    pub angular_diameter_mpc: f64,
    pub luminosity_mpc: f64,
    pub volume_mpc3_per_sr_per_redshift: f64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct KinematicOutcome {
    pub state: OutputState,
    pub q: f64,
    pub jerk: f64,
    pub q0_within_piecewise_model: f64,
    pub has_jerk: u32,
    pub has_q0: u32,
    pub q_convention: u32,
    pub jerk_availability: u32,
    pub bin: u64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct ExpansionRow {
    pub struct_size: u32,
    pub abi_version: u32,
    pub model_index: u64,
    pub query_index: u64,
    pub node_index: u64,
    pub has_node: u32,
    pub admission_status: u32,
    pub expansion: ExpansionOutcome,
    pub radial: RadialOutcome,
    pub luminosity_shape: ScalarOutcome,
    pub clock: ClockOutcome,
    pub physical: PhysicalOutcome,
    pub kinematics: KinematicOutcome,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct ExpansionNode {
    pub struct_size: u32,
    pub abi_version: u32,
    pub model_index: u64,
    pub z_expansion: f64,
    pub callbacks: u64,
    pub segment_visits: u64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct ExpansionModelView {
    pub struct_size: u32,
    pub abi_version: u32,
    pub model_index: u64,
    pub preparation_status: u32,
    pub evaluation_status: u32,
    pub numerical_status: u32,
    pub reserved: u32,
    pub row_offset: u64,
    pub row_count: u64,
    pub source: ExpansionSpec,
    pub model_id: Bytes,
    pub constants_id: Bytes,
    pub radial_equation_id: Bytes,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct ProjectionPolicy {
    pub struct_size: u32,
    pub abi_version: u32,
    pub has_integration: u32,
    pub maximum_depth: u32,
    pub absolute_tolerance: f64,
    pub relative_tolerance: f64,
    pub maximum_evaluations_per_integral: u64,
    pub maximum_queries: u64,
    pub maximum_callbacks: u64,
    pub maximum_segment_visits: u64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct SourceEffectSpec {
    pub struct_size: u32,
    pub abi_version: u32,
    pub effect: u32,
    pub reserved: u32,
    pub parameters: F64Buffer,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct SupernovaModel {
    pub struct_size: u32,
    pub abi_version: u32,
    pub geometry: u32,
    pub reserved: u32,
    pub expansion: ExpansionSpec,
    pub source_effect: SourceEffectSpec,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct MagnitudeCoordinate {
    pub struct_size: u32,
    pub abi_version: u32,
    pub z_expansion: f64,
    pub observer_redshift: f64,
    pub observer_convention: u32,
    pub reserved: u32,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct MagnitudeSelection {
    pub struct_size: u32,
    pub abi_version: u32,
    pub kind: u32,
    pub reserved: u32,
    pub source_indices: U64Buffer,
    pub coordinates: *const MagnitudeCoordinate,
    pub coordinate_count: u64,
    pub coordinate_byte_length: u64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct SupernovaPreparationPolicy {
    pub struct_size: u32,
    pub abi_version: u32,
    pub arithmetic: u32,
    pub reserved: u32,
    pub maximum_selected_rows: u64,
    pub maximum_matrix_elements: u64,
    pub maximum_string_bytes: u64,
    pub maximum_native_bytes: u64,
    pub maximum_forward_sensitivity: f64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct SupernovaEvaluationPolicy {
    pub struct_size: u32,
    pub abi_version: u32,
    pub arithmetic: u32,
    pub requested: u32,
    pub projection: ProjectionPolicy,
    pub maximum_models: u64,
    pub maximum_array_elements: u64,
    pub maximum_native_bytes: u64,
    pub maximum_forward_sensitivity: f64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct SupernovaBatch {
    pub struct_size: u32,
    pub abi_version: u32,
    pub models: *const SupernovaModel,
    pub model_count: u64,
    pub model_byte_length: u64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct SupernovaView {
    pub struct_size: u32,
    pub abi_version: u32,
    pub status: u32,
    pub preparation_status: u32,
    pub preparation_numerical_status: u32,
    pub arithmetic: u32,
    pub retained_bytes: u64,
    pub source: ObservationDescriptor,
    pub ordered_ids: Strings,
    pub selected_source_indices: U64Buffer,
    pub coordinates: *const MagnitudeCoordinate,
    pub coordinate_count: u64,
    pub coordinate_byte_length: u64,
    pub arithmetic_id: Bytes,
    pub score_id: Bytes,
    pub shape_convention: Bytes,
    pub offset_convention: Bytes,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct ProfilePayload {
    pub state: OutputState,
    pub offset_coefficient: f64,
    pub quadratic: f64,
    pub relative_profile_score: f64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct ProfileDiagnostics {
    pub state: OutputState,
    pub backward_residual: f64,
    pub estimated_forward_sensitivity: f64,
    pub coefficient_backward_residual: f64,
    pub coefficient_forward_sensitivity: f64,
    pub residual_l1: f64,
    pub solution_norm_inf: f64,
    pub adjusted_residual_l1: f64,
    pub adjusted_solution_norm_inf: f64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct SupernovaRow {
    pub struct_size: u32,
    pub abi_version: u32,
    pub model_index: u64,
    pub source: SupernovaModel,
    pub status: u32,
    pub background_status: u32,
    pub numerical_status: u32,
    pub profile_status: u32,
    pub geometry_state: OutputState,
    pub effect_state: OutputState,
    pub corrected_state: OutputState,
    pub profiled_state: OutputState,
    pub score: ProfilePayload,
    pub diagnostics: ProfileDiagnostics,
    pub geometric_shape: F64Buffer,
    pub magnitude_effect: F64Buffer,
    pub corrected_residuals: F64Buffer,
    pub profiled_residuals: F64Buffer,
    pub background_node_indices: U64Buffer,
    pub callbacks: u64,
    pub segment_visits: u64,
    pub model_id: Bytes,
    pub hypothesis_id: Bytes,
    pub arithmetic_id: Bytes,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct BaoModel {
    pub struct_size: u32,
    pub abi_version: u32,
    pub geometry: u32,
    pub reserved: u32,
    pub expansion: ExpansionSpec,
    pub h0_rd_km_s: f64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct BaoPreparationPolicy {
    pub struct_size: u32,
    pub abi_version: u32,
    pub arithmetic: u32,
    pub reserved: u32,
    pub maximum_queries: u64,
    pub maximum_matrix_elements: u64,
    pub maximum_string_bytes: u64,
    pub maximum_native_bytes: u64,
    pub maximum_forward_sensitivity: f64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct BaoEvaluationPolicy {
    pub struct_size: u32,
    pub abi_version: u32,
    pub arithmetic: u32,
    pub requested: u32,
    pub projection: ProjectionPolicy,
    pub maximum_models: u64,
    pub maximum_array_elements: u64,
    pub maximum_native_bytes: u64,
    pub maximum_forward_sensitivity: f64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct BaoBatch {
    pub struct_size: u32,
    pub abi_version: u32,
    pub models: *const BaoModel,
    pub model_count: u64,
    pub model_byte_length: u64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct BaoSource {
    pub struct_size: u32,
    pub abi_version: u32,
    pub role: u32,
    pub covariance_unit: u32,
    pub queries: *const BaoQuery,
    pub query_count: u64,
    pub query_byte_length: u64,
    pub observed: F64Buffer,
    pub covariance: F64Buffer,
    pub ordered_ids: Strings,
    pub covariance_axis_ids: Strings,
    pub table_identity: Bytes,
    pub covariance_identity: Bytes,
    pub ordering_provenance: Bytes,
    pub calibration_provenance: Bytes,
    pub dependence_provenance: Bytes,
    pub redshift_convention: Bytes,
    pub ruler_convention: Bytes,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct BaoView {
    pub struct_size: u32,
    pub abi_version: u32,
    pub status: u32,
    pub numerical_status: u32,
    pub arithmetic: u32,
    pub reserved: u32,
    pub retained_bytes: u64,
    pub source: BaoSource,
    pub arithmetic_id: Bytes,
    pub density_id: Bytes,
    pub equation_id: Bytes,
    pub ruler_convention_id: Bytes,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct DensityPayload {
    pub state: OutputState,
    pub quadratic: f64,
    pub log_determinant: f64,
    pub log_normalization: f64,
    pub log_density: f64,
    pub backward_residual: f64,
    pub estimated_forward_sensitivity: f64,
}
#[allow(non_snake_case)]
#[repr(C)]
pub struct BaoRow {
    pub struct_size: u32,
    pub abi_version: u32,
    pub model_index: u64,
    pub source: BaoModel,
    pub background_status: u32,
    pub numerical_status: u32,
    pub predictions_state: OutputState,
    pub residuals_state: OutputState,
    pub density: DensityPayload,
    pub predictions: F64Buffer,
    pub residuals: F64Buffer,
    pub background_node_indices: U64Buffer,
    pub callbacks: u64,
    pub segment_visits: u64,
    pub model_id: Bytes,
    pub arithmetic_id: Bytes,
}
unsafe extern "C" {
    pub fn irred_add(
        a: *const Buffer,
        b: *const Buffer,
        fault: u32,
        out: *mut *mut std::ffi::c_void,
    ) -> u32;
    pub fn irred_result_view(r: *const std::ffi::c_void, data: *mut *const i64, n: *mut u64)
        -> u32;
    pub fn irred_result_destroy(r: *mut std::ffi::c_void) -> u32;
    pub fn irred_convert_quantities(
        values: *const F64Buffer,
        source: *const QuantityMetadata,
        target: *const QuantityMetadata,
        out: *mut *mut std::ffi::c_void,
    ) -> u32;
    pub fn irred_result_f64_view(
        r: *const std::ffi::c_void,
        data: *mut *const f64,
        status: *mut *const u32,
        n: *mut u64,
    ) -> u32;
    pub fn irred_numerics_evaluate(
        operation: u32,
        values: *const F64Buffer,
        out: *mut *mut std::ffi::c_void,
    ) -> u32;
    pub fn irred_result_numerics_view(
        r: *const std::ffi::c_void,
        data: *mut *const f64,
        status: *mut *const u32,
        error_estimate: *mut *const f64,
        evaluations: *mut *const u64,
        n: *mut u64,
    ) -> u32;
    pub fn irred_prepare_observations(
        descriptor: *const ObservationDescriptor,
        policy: *const ObservationPolicy,
        out: *mut *mut std::ffi::c_void,
        semantic_status: *mut u32,
    ) -> u32;
    pub fn irred_observation_source_view(
        prepared: *const std::ffi::c_void,
        descriptor: *mut ObservationDescriptor,
    ) -> u32;
    pub fn irred_observation_select(
        prepared: *const std::ffi::c_void,
        selection: u32,
        out: *mut *mut std::ffi::c_void,
        semantic_status: *mut u32,
    ) -> u32;
    pub fn irred_result_selection_view(
        result: *const std::ffi::c_void,
        mask: *mut *const u8,
        mask_length: *mut u64,
        indices: *mut *const u64,
        index_length: *mut u64,
    ) -> u32;
    pub fn irred_observation_destroy(prepared: *mut std::ffi::c_void) -> u32;
    pub fn irred_gaussian_prepare(
        observations: *const std::ffi::c_void,
        selection: u32,
        policy: *const GaussianPolicy,
        out: *mut *mut std::ffi::c_void,
        semantic: *mut u32,
        numerical_status: *mut u32,
    ) -> u32;
    pub fn irred_gaussian_proper_offset(
        gaussian: *const std::ffi::c_void,
        prior: *const GaussianPrior,
        policy: *const GaussianPolicy,
        out: *mut *mut std::ffi::c_void,
        semantic: *mut u32,
        numerical_status: *mut u32,
    ) -> u32;
    pub fn irred_gaussian_source_view(
        gaussian: *const std::ffi::c_void,
        out: *mut GaussianView,
    ) -> u32;
    pub fn irred_gaussian_prior_view(
        gaussian: *const std::ffi::c_void,
        index: u64,
        out: *mut GaussianPrior,
    ) -> u32;
    pub fn irred_gaussian_evaluate(
        gaussian: *const std::ffi::c_void,
        batch: *const GaussianBatch,
        policy: *const GaussianPolicy,
        out: *mut *mut std::ffi::c_void,
    ) -> u32;
    pub fn irred_gaussian_result_view(
        result: *const std::ffi::c_void,
        rows: *mut *const GaussianRow,
        length: *mut u64,
    ) -> u32;
    pub fn irred_gaussian_destroy(gaussian: *mut std::ffi::c_void) -> u32;
    pub fn irred_gaussian_result_destroy(result: *mut std::ffi::c_void) -> u32;
    pub fn irred_gaussian_selection_view(
        gaussian: *const std::ffi::c_void,
        index: u64,
        out: *mut GaussianSelection,
    ) -> u32;
    pub fn irred_expansion_evaluate(
        batch: *const ExpansionBatch,
        policy: *const ExpansionPolicy,
        out: *mut *mut std::ffi::c_void,
    ) -> u32;
    pub fn irred_expansion_result_view(
        result: *const std::ffi::c_void,
        rows: *mut *const ExpansionRow,
        count: *mut u64,
        status: *mut u32,
        numerical_status: *mut u32,
        callbacks: *mut u64,
        segment_visits: *mut u64,
    ) -> u32;
    pub fn irred_expansion_result_models(
        result: *const std::ffi::c_void,
        models: *mut *const ExpansionModelView,
        count: *mut u64,
        available: *mut u32,
    ) -> u32;
    pub fn irred_expansion_result_queries(
        result: *const std::ffi::c_void,
        queries: *mut *const ExpansionRequest,
        count: *mut u64,
        available: *mut u32,
    ) -> u32;
    pub fn irred_expansion_result_nodes(
        result: *const std::ffi::c_void,
        nodes: *mut *const ExpansionNode,
        count: *mut u64,
    ) -> u32;
    pub fn irred_expansion_result_destroy(result: *mut std::ffi::c_void) -> u32;
    pub fn irred_observation_retained_bytes(
        source: *const std::ffi::c_void,
        bytes: *mut u64,
    ) -> u32;
    pub fn irred_supernova_prepare(
        source: *const std::ffi::c_void,
        selection: *const MagnitudeSelection,
        policy: *const SupernovaPreparationPolicy,
        out: *mut *mut std::ffi::c_void,
    ) -> u32;
    pub fn irred_supernova_source_view(
        source: *const std::ffi::c_void,
        view: *mut SupernovaView,
    ) -> u32;
    pub fn irred_supernova_evaluate(
        source: *const std::ffi::c_void,
        batch: *const SupernovaBatch,
        policy: *const SupernovaEvaluationPolicy,
        out: *mut *mut std::ffi::c_void,
    ) -> u32;
    pub fn irred_supernova_result_view(
        result: *const std::ffi::c_void,
        rows: *mut *const SupernovaRow,
        count: *mut u64,
        status: *mut u32,
        numerical_status: *mut u32,
        callbacks: *mut u64,
        segments: *mut u64,
    ) -> u32;
    pub fn irred_supernova_result_source_view(
        result: *const std::ffi::c_void,
        view: *mut SupernovaView,
        available: *mut u32,
    ) -> u32;
    pub fn irred_supernova_destroy(source: *mut std::ffi::c_void) -> u32;
    pub fn irred_supernova_result_destroy(result: *mut std::ffi::c_void) -> u32;
    pub fn irred_bao_prepare(
        source: *const BaoSource,
        policy: *const BaoPreparationPolicy,
        out: *mut *mut std::ffi::c_void,
    ) -> u32;
    pub fn irred_bao_source_view(source: *const std::ffi::c_void, view: *mut BaoView) -> u32;
    pub fn irred_bao_evaluate(
        source: *const std::ffi::c_void,
        batch: *const BaoBatch,
        policy: *const BaoEvaluationPolicy,
        out: *mut *mut std::ffi::c_void,
    ) -> u32;
    pub fn irred_bao_result_view(
        result: *const std::ffi::c_void,
        rows: *mut *const BaoRow,
        count: *mut u64,
        status: *mut u32,
        numerical_status: *mut u32,
        callbacks: *mut u64,
        segments: *mut u64,
    ) -> u32;
    pub fn irred_bao_result_source_view(
        result: *const std::ffi::c_void,
        view: *mut BaoView,
        available: *mut u32,
    ) -> u32;
    pub fn irred_bao_destroy(source: *mut std::ffi::c_void) -> u32;
    pub fn irred_bao_result_destroy(result: *mut std::ffi::c_void) -> u32;
    pub fn irred_observation_preparation_bytes(
        descriptor: *const ObservationDescriptor,
        bytes: *mut u64,
    ) -> u32;
}
#[derive(Clone, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct MetadataFields {
    pub unit: String,
    pub role: String,
    pub frame: String,
    pub convention: String,
    pub constant_set: String,
}
pub fn tag_id(group: &str, label: &str) -> Option<u32> {
    match (group, label) {
        ("unit", "one") => Some(1),
        ("unit", "metre") => Some(2),
        ("unit", "kilometre") => Some(3),
        ("unit", "second") => Some(4),
        ("unit", "day") => Some(5),
        ("unit", "inverse_second") => Some(6),
        ("unit", "parsec") => Some(7),
        ("unit", "megaparsec") => Some(8),
        ("unit", "km_per_s_per_mpc") => Some(9),
        ("role", "ratio") => Some(1),
        ("role", "redshift") => Some(2),
        ("role", "physical_length") => Some(3),
        ("role", "comoving_distance") => Some(4),
        ("role", "luminosity_distance") => Some(5),
        ("role", "angular_diameter_distance") => Some(6),
        ("role", "duration") => Some(7),
        ("role", "expansion_rate") => Some(8),
        ("frame", "none") => Some(0),
        ("frame", "heliocentric") => Some(1),
        ("frame", "cmb") => Some(2),
        ("frame", "model") => Some(3),
        ("convention", "none") => Some(0),
        ("convention", "physical") => Some(1),
        ("convention", "comoving_a0_one") => Some(2),
        ("constant_set", "SI-IAU-definitions-v1") => Some(1),
        ("quantity_status", "ok") => Some(0),
        ("quantity_status", "unknown_unit") => Some(1),
        ("quantity_status", "dimension_mismatch") => Some(2),
        ("quantity_status", "role_mismatch") => Some(3),
        ("quantity_status", "missing_convention") => Some(4),
        ("quantity_status", "unsupported_transform") => Some(5),
        ("quantity_status", "nonfinite_input") => Some(6),
        ("quantity_status", "overflow") => Some(7),
        ("quantity_status", "underflow") => Some(8),
        ("quantity_status", "constant_set_mismatch") => Some(9),
        ("quantity_status", "invalid_domain") => Some(10),
        ("quantity_status", "invalid_batch") => Some(11),
        _ => None,
    }
}
pub fn quantity_status_name(value: u32) -> Option<&'static str> {
    match value {
        0 => Some("ok"),
        1 => Some("unknown_unit"),
        2 => Some("dimension_mismatch"),
        3 => Some("role_mismatch"),
        4 => Some("missing_convention"),
        5 => Some("unsupported_transform"),
        6 => Some("nonfinite_input"),
        7 => Some("overflow"),
        8 => Some("underflow"),
        9 => Some("constant_set_mismatch"),
        10 => Some("invalid_domain"),
        11 => Some("invalid_batch"),
        _ => None,
    }
}
#[derive(Clone, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct ObservationMetadataFields {
    pub profile: String,
    pub role: String,
    pub unit: String,
    pub calibration: String,
    pub uncertainty: String,
    pub uncertainty_unit: String,
    pub component: String,
}
pub fn observation_tag_id(group: &str, label: &str) -> Option<u32> {
    match (group, label) {
        ("profile", "pantheon_plus_released_v1") => Some(0),
        ("profile", "gaussian_fixture_v1") => Some(1),
        ("profile", "fits_length_fixture_v1") => Some(2),
        ("profile", "typed_magnitude_covariance") => Some(3),
        ("role", "observed_measurement") => Some(0),
        ("role", "released_fitted_summary") => Some(1),
        ("role", "synthetic_control") => Some(2),
        ("role", "posterior_summary") => Some(3),
        ("unit", "magnitude") => Some(0),
        ("unit", "metre") => Some(1),
        ("calibration", "unknown") => Some(0),
        ("calibration", "released_corrected") => Some(1),
        ("calibration", "not_applicable") => Some(2),
        ("uncertainty", "none") => Some(0),
        ("uncertainty", "covariance") => Some(1),
        ("uncertainty", "precision") => Some(2),
        ("uncertainty_unit", "none") => Some(0),
        ("uncertainty_unit", "magnitude_squared") => Some(1),
        ("uncertainty_unit", "inverse_magnitude_squared") => Some(2),
        ("uncertainty_unit", "metre_squared") => Some(3),
        ("uncertainty_unit", "inverse_metre_squared") => Some(4),
        ("component", "unknown") => Some(0),
        ("component", "statistical") => Some(1),
        ("component", "systematic") => Some(2),
        ("component", "total") => Some(3),
        ("selection", "all") => Some(0),
        ("selection", "pantheon_zhd_gt_001") => Some(1),
        ("status", "ok") => Some(0),
        ("status", "invalid_shape") => Some(1),
        ("status", "invalid_identity") => Some(2),
        ("status", "incompatible_semantics") => Some(3),
        ("status", "missing_required_value") => Some(4),
        ("status", "nonfinite_required_value") => Some(5),
        ("status", "resource_limit") => Some(6),
        _ => None,
    }
}
pub fn observation_status_name(value: u32) -> Option<&'static str> {
    match value {
        0 => Some("ok"),
        1 => Some("invalid_shape"),
        2 => Some("invalid_identity"),
        3 => Some("incompatible_semantics"),
        4 => Some("missing_required_value"),
        5 => Some("nonfinite_required_value"),
        6 => Some("resource_limit"),
        _ => None,
    }
}
pub fn numerical_operation_id(label: &str) -> Option<u32> {
    match label {
        "compensated_sum" => Some(1),
        "log_sum_exp" => Some(2),
        "log1p" => Some(3),
        "expm1" => Some(4),
        "log_gamma_positive" => Some(5),
        _ => None,
    }
}
pub fn numerical_status_name(value: u32) -> Option<&'static str> {
    match value {
        0 => Some("ok"),
        1 => Some("invalid_input"),
        2 => Some("nonfinite_input"),
        3 => Some("overflow"),
        4 => Some("work_limit"),
        5 => Some("outside_domain"),
        6 => Some("singular"),
        7 => Some("not_positive_definite"),
        8 => Some("conditioning_budget_exceeded"),
        _ => None,
    }
}
pub fn numerical_output_length(method: &str, input: usize) -> Option<usize> {
    match method {
        "compensated_sum" => Some(1),
        "log_sum_exp" => Some(1),
        "log1p" => Some(input),
        "expm1" => Some(input),
        "log_gamma_positive" => Some(input),
        _ => None,
    }
}
