// Generated by tools/generate_abi.py; edit schema/abi.json.
pub const ABI_VERSION: u32 = 1;
pub const OK: u32 = 0;
pub const ABI_MISMATCH: u32 = 1;
pub const INVALID_INPUT: u32 = 2;
pub const OVERFLOW: u32 = 3;
pub const ALLOCATION_FAILURE: u32 = 4;
pub const EXCEPTION: u32 = 5;
#[repr(C)]
pub struct Buffer {
    pub struct_size: u32,
    pub abi_version: u32,
    pub element_type: u32,
    pub reserved: u32,
    pub data: *const i64,
    pub length: u64,
    pub byte_length: u64,
}
unsafe extern "C" {
    pub fn cosmo_add(
        a: *const Buffer,
        b: *const Buffer,
        fault: u32,
        out: *mut *mut std::ffi::c_void,
    ) -> u32;
    pub fn cosmo_result_view(r: *const std::ffi::c_void, data: *mut *const i64, n: *mut u64)
        -> u32;
    pub fn cosmo_result_destroy(r: *mut std::ffi::c_void) -> u32;
}
